import { EXTRA_PLATFORMS } from "./catalog-extra";
import { FRIEND_PLATFORMS } from "./catalog-friends";
import type { Origin, Platform, Threat, UasClass } from "./types";

function p(row: Platform): Platform {
  return row;
}

export const PLATFORMS: Platform[] = [
  p({
    id: "dji-mini-4-pro",
    name: "Mini 4 Pro",
    manufacturer: "DJI",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "consumer",
    threat: "faible",
    massKg: 0.249,
    enduranceMin: 34,
    rangeKm: 20,
    ceilingM: 1500,
    cruiseKmh: 36,
    maxKmh: 58,
    rfBands: ["2.400–2.483 GHz", "5.725–5.850 GHz"],
    protocol: "OcuSync 4",
    remoteId: true,
    payload: "Caméra 4K / 48 MP, pas d'emport",
    cues: {
      rf: "OcuSync 4, sauts de fréquence ISM, Remote ID broadcast.",
      visual: "Quad compact pliable, bras avant relevés, hélice 2 pales.",
      kinematic: "Vol stationnaire, Vmax ~16 m/s, plafond bas.",
      acoustic: "BPF quad ~80–140 Hz, signature urbaine typique.",
    },
    notes: "UAS grand public le plus fréquent en zone urbaine. Mandat: origine DJI / Chine.",
  }),
  p({
    id: "dji-mavic-3t",
    name: "Mavic 3T",
    manufacturer: "DJI",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "moderee",
    massKg: 0.92,
    enduranceMin: 45,
    rangeKm: 15,
    ceilingM: 6000,
    cruiseKmh: 54,
    maxKmh: 75,
    rfBands: ["2.400–2.483 GHz", "5.725–5.850 GHz"],
    protocol: "OcuSync 3 Enterprise",
    remoteId: true,
    payload: "EO 4K + IR 640, télémètre laser",
    cues: {
      rf: "OcuSync 3E, downlink vidéo dual-band, RID.",
      visual: "Quad pliable, nacelle bi-capteur visible sous le nez.",
      kinematic: "Hover stable, 15 m/s cruise, profil ISR rasant.",
      acoustic: "Quad plus grave que Mini, ~70–110 Hz.",
    },
    notes: "Plateforme ISR tactique civile très répandue auprès des sociétés de sécurité.",
  }),
  p({
    id: "dji-matrice-30t",
    name: "Matrice 30T",
    manufacturer: "DJI",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "moderee",
    massKg: 3.77,
    enduranceMin: 41,
    rangeKm: 15,
    ceilingM: 7000,
    cruiseKmh: 61,
    maxKmh: 82,
    rfBands: ["2.400–2.483 GHz", "5.725–5.850 GHz"],
    protocol: "OcuSync 3 Enterprise",
    remoteId: true,
    payload: "EO/IR/laser, projecteur, haut-parleur",
    cues: {
      rf: "OcuSync 3E longue portée, liaison secondaire 2.4/5.8.",
      visual: "Châssis fermé, train large, nacelle multi-capteurs.",
      kinematic: "Résiste au vent 15 m/s, transit 23 m/s.",
      acoustic: "Quad 4 batteries, BPF plus ample ~60–90 Hz.",
    },
    notes: "Standard des missions de surveillance périmétrique et minières.",
  }),
  p({
    id: "dji-matrice-350",
    name: "Matrice 350 RTK",
    manufacturer: "DJI",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "moderee",
    massKg: 6.47,
    enduranceMin: 55,
    rangeKm: 20,
    ceilingM: 7000,
    cruiseKmh: 54,
    maxKmh: 82,
    rfBands: ["2.400–2.483 GHz", "5.725–5.850 GHz"],
    protocol: "OcuSync 3 Enterprise",
    remoteId: true,
    payload: "Nacelles Zenmuse (H20N, L2 lidar), RTK",
    cues: {
      rf: "OcuSync 3E + module RTK GNSS L1/L2.",
      visual: "X-frame ouvert, double batterie TB65, mât RTK.",
      kinematic: "Hover de précision, emport jusqu'à ~2.7 kg.",
      acoustic: "Quatre rotors larges, ~55–85 Hz.",
    },
    notes: "Cheval de bataille ISR/mapping. Identification souvent par RTK + OcuSync.",
  }),
  p({
    id: "dji-agras-t50",
    name: "Agras T50",
    manufacturer: "DJI",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "agriculture",
    threat: "faible",
    massKg: 39.9,
    enduranceMin: 20,
    rangeKm: 2,
    ceilingM: 200,
    cruiseKmh: 36,
    maxKmh: 50,
    rfBands: ["2.400–2.483 GHz"],
    protocol: "DJI Agras link",
    remoteId: true,
    payload: "Cuve 40 L, radar omnidir.",
    cues: {
      rf: "Liaison Agras, faible distance, radar anticollision 24 GHz.",
      visual: "Hexa/octo massif, rampes de buses, réservoir central.",
      kinematic: "Vol rasant < 10 m, allers-retours de parcelle.",
      acoustic: "Très bruyant, BPF grave < 60 Hz.",
    },
    notes: "Signature agricole caractéristique. Faible menace mais RCS élevé.",
  }),
  p({
    id: "autel-evo-max-4t",
    name: "EVO Max 4T",
    manufacturer: "Autel Robotics",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "moderee",
    massKg: 1.6,
    enduranceMin: 42,
    rangeKm: 20,
    ceilingM: 7000,
    cruiseKmh: 54,
    maxKmh: 82,
    rfBands: ["2.400–2.483 GHz", "5.8 GHz", "900 MHz"],
    protocol: "Autel SkyLink 3.0",
    remoteId: true,
    payload: "EO 4K + IR 640 + télémètre + grand angle",
    cues: {
      rf: "SkyLink 3.0, bande 900 MHz possible hors Europe.",
      visual: "Quad fermé, nacelle 4 capteurs, sans RTK mât DJI.",
      kinematic: "Hover, 23 m/s max, évitement 360°.",
      acoustic: "Quad médium, proche Mavic 3 mais timbre Autel.",
    },
    notes: "Alternative chinoise à DJI Enterprise. Protocole SkyLink distinct d'OcuSync.",
  }),
  p({
    id: "autel-dragonfish",
    name: "Dragonfish",
    manufacturer: "Autel Robotics",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "vtol",
    role: "isr",
    threat: "elevee",
    massKg: 7.5,
    enduranceMin: 180,
    rangeKm: 30,
    ceilingM: 6000,
    cruiseKmh: 108,
    maxKmh: 108,
    rfBands: ["2.4 GHz", "5.8 GHz"],
    protocol: "Autel SkyLink VTOL",
    remoteId: true,
    payload: "Nacelle gimbal EO/IR interchangeable",
    cues: {
      rf: "SkyLink longue endurance, handover VTOL.",
      visual: "Aile + 2 rotors lift + propulseur arrière.",
      kinematic: "Décollage vertical puis transit aile ~30 m/s.",
      acoustic: "Rotors lift au décollage, puis hélice unique.",
    },
    notes: "VTOL ISR. La transition hover→aile est un marqueur cinématique fort.",
  }),
  p({
    id: "xag-p100",
    name: "P100 Pro",
    manufacturer: "XAG",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "agriculture",
    threat: "faible",
    massKg: 32,
    enduranceMin: 18,
    rangeKm: 2,
    ceilingM: 150,
    cruiseKmh: 43,
    maxKmh: 48,
    rfBands: ["2.4 GHz"],
    protocol: "XAG SuperX",
    remoteId: false,
    payload: "Cuve 40 kg, pulvérisation",
    cues: {
      rf: "SuperX, pas de Remote ID systématique.",
      visual: "Quad agricole, bras épais, buses.",
      kinematic: "Passages linéaires rasant.",
      acoustic: "Grave, similaire Agras.",
    },
    notes: "Constructeur chinois hors DJI. Fréquent sur périmètres agricoles.",
  }),
  p({
    id: "ziyan-blowfish",
    name: "Blowfish A2",
    manufacturer: "Ziyan",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "elevee",
    massKg: 11,
    enduranceMin: 35,
    rangeKm: 15,
    ceilingM: 3000,
    cruiseKmh: 72,
    maxKmh: 130,
    rfBands: ["2.4 GHz", "1.4 GHz"],
    protocol: "Ziyan FHSS",
    remoteId: false,
    payload: "EO/IR, possible emport léger",
    cues: {
      rf: "FHSS propriétaire, pas de RID, parfois 1.4 GHz.",
      visual: "Hélicoptère coaxial (pas un quad), fuselage étroit.",
      kinematic: "Vitesse élevée pour un rotary, pas de hover long DJI.",
      acoustic: "Coaxial 2 rotors, signature hélico légère.",
    },
    notes: "UAS para-militaire chinois. Confusion fréquente avec un hélicoptère léger.",
  }),
  p({
    id: "wing-loong-2",
    name: "Wing Loong II",
    manufacturer: "AVIC / CAC",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 4200,
    enduranceMin: 1200,
    rangeKm: 1500,
    ceilingM: 9000,
    cruiseKmh: 280,
    maxKmh: 370,
    rfBands: ["L-band LOS", "SATCOM Ku/Ka"],
    protocol: "Liaison MALE propriétaire + SATCOM",
    remoteId: false,
    payload: "Jusqu'à 480 kg (EO/IR + armement)",
    cues: {
      rf: "SATCOM Ku/Ka + LOS L-band, pas ISM grand public.",
      visual: "MALE aile haute ~20.5 m, V-tail, nez boule optronique.",
      kinematic: "Transit 70–100 m/s, virages larges, altitude 5–9 km.",
      acoustic: "Turbo-hélice, inaudible au sol en croisière haute.",
    },
    notes: "UCAV MALE d'export. RCS et cinématique sans rapport avec un DJI.",
  }),
  p({
    id: "ch-4b",
    name: "CH-4B Rainbow",
    manufacturer: "CASC / CAAA",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 1330,
    enduranceMin: 1800,
    rangeKm: 500,
    ceilingM: 7200,
    cruiseKmh: 180,
    maxKmh: 235,
    rfBands: ["L-band LOS", "SATCOM"],
    protocol: "CASC C2",
    remoteId: false,
    payload: "345 kg, 6 points d'emport",
    cues: {
      rf: "LOS L-band + SATCOM, absence totale ISM.",
      visual: "MALE ~18 m, empennage en V, longeron d'aile droit.",
      kinematic: "Endurance extrême, 50–65 m/s, orbites ISR.",
      acoustic: "Moteur à piston, discret à haute altitude.",
    },
    notes: "Famille Rainbow, largement exportée. Distinct du Wing Loong par la masse et l'empennage.",
  }),
  p({
    id: "ch-5",
    name: "CH-5 Rainbow",
    manufacturer: "CASC / CAAA",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 3000,
    enduranceMin: 2400,
    rangeKm: 2000,
    ceilingM: 7000,
    cruiseKmh: 180,
    maxKmh: 220,
    rfBands: ["SATCOM Ku", "LOS C-band"],
    protocol: "CASC C2 longue endurance",
    remoteId: false,
    payload: "1000 kg",
    cues: {
      rf: "SATCOM dominant, C-band LOS de relais.",
      visual: "MALE large (~21 m), plus massif que CH-4.",
      kinematic: "Orbites longues, 50 m/s, plafond 7 km.",
      acoustic: "Turbo-hélice, sol silencieux à l'altitude de travail.",
    },
    notes: "Évolution lourde de la famille Rainbow.",
  }),
  p({
    id: "tb-001",
    name: "TB-001 Twin-Tailed Scorpion",
    manufacturer: "Tengden",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 2800,
    enduranceMin: 2100,
    rangeKm: 6000,
    ceilingM: 8000,
    cruiseKmh: 250,
    maxKmh: 300,
    rfBands: ["SATCOM", "LOS"],
    protocol: "Tengden C2",
    remoteId: false,
    payload: "1 200 kg, bimoteur",
    cues: {
      rf: "SATCOM + LOS, signature bimoteur.",
      visual: "Double queue, deux moteurs à hélice sous aile.",
      kinematic: "MALE bimoteur, 70 m/s, grande autonomie.",
      acoustic: "Deux foyers propulsifs, unique parmi les MALE chinois courants.",
    },
    notes: "Silhouette à double dérive très discriminante en EO.",
  }),
  p({
    id: "gj-11",
    name: "GJ-11 Sharp Sword",
    manufacturer: "AVIC / Shenyang",
    origin: "CN",
    originLabel: "Chine",
    uasClass: "ucav",
    role: "strike",
    threat: "critique",
    massKg: 10000,
    enduranceMin: 360,
    rangeKm: 1500,
    ceilingM: 13000,
    cruiseKmh: 750,
    maxKmh: 1000,
    rfBands: ["SATCOM faible PAPR", "liaison furtive"],
    protocol: "Liaison LPI / SATCOM",
    remoteId: false,
    payload: "Soute interne, UCAV furtif",
    cues: {
      rf: "LPI, difficile en RF classique — privilégier radar 3D + EO.",
      visual: "Aile volante, sans empennage, RCS très bas.",
      kinematic: "Jet subsonique haut, 200 m/s+, pas de hover.",
      acoustic: "Turboréacteur, signature jet.",
    },
    notes: "UCAV furtif. L'identification RF seule est insuffisante — fusion radar/EO obligatoire.",
  }),
  p({
    id: "tb2",
    name: "Bayraktar TB2",
    manufacturer: "Baykar",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 700,
    enduranceMin: 1620,
    rangeKm: 300,
    ceilingM: 7600,
    cruiseKmh: 130,
    maxKmh: 220,
    rfBands: ["LOS C-band", "SATCOM (variantes)"],
    protocol: "Baykar C2",
    remoteId: false,
    payload: "150 kg, 4 points d'emport (MAM-L / MAM-C)",
    cues: {
      rf: "LOS C-band caractéristique Baykar, pas ISM.",
      visual: "Queue en V inversé, aile droite 12 m, boule nez.",
      kinematic: "70–120 km/h, orbites ISR 5–7 km, endurance > 20 h.",
      acoustic: "Rotax 912, discret à l'altitude de travail.",
    },
    notes: "UCAV d'export le plus documenté. Cinématique et silhouette très stables pour matching.",
  }),
  p({
    id: "tb3",
    name: "Bayraktar TB3",
    manufacturer: "Baykar",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 1450,
    enduranceMin: 1440,
    rangeKm: 1900,
    ceilingM: 10000,
    cruiseKmh: 160,
    maxKmh: 300,
    rfBands: ["LOS", "SATCOM"],
    protocol: "Baykar C2 naval",
    remoteId: false,
    payload: "280 kg, ailes repliables",
    cues: {
      rf: "C2 Baykar, SATCOM plus fréquent que TB2.",
      visual: "Proche TB2 agrandi, ailes à charnière, empennage V.",
      kinematic: "Plus rapide et plus haut que TB2.",
      acoustic: "Moteur plus puissant, toujours piston/hélice.",
    },
    notes: "Version embarquée / allongée du TB2. Confusion possible avec TB2 en EO lointain.",
  }),
  p({
    id: "akinci",
    name: "Bayraktar Akıncı",
    manufacturer: "Baykar",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 5500,
    enduranceMin: 1440,
    rangeKm: 6500,
    ceilingM: 12192,
    cruiseKmh: 240,
    maxKmh: 361,
    rfBands: ["SATCOM Ku", "LOS"],
    protocol: "Baykar C2 lourd",
    remoteId: false,
    payload: "1 350 kg, bimoteur",
    cues: {
      rf: "SATCOM Ku dominant, LOS relais.",
      visual: "MALE bimoteur ~20 m, double hélice, empennage V.",
      kinematic: "200–360 km/h, plafond 12 km.",
      acoustic: "Deux turbos, inaudible au sol en croisière.",
    },
    notes: "Classe supérieure au TB2. Silhouette bimoteur discriminante.",
  }),
  p({
    id: "kizilelma",
    name: "Bayraktar Kızılelma",
    manufacturer: "Baykar",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "ucav",
    role: "strike",
    threat: "critique",
    massKg: 8500,
    enduranceMin: 300,
    rangeKm: 900,
    ceilingM: 13700,
    cruiseKmh: 800,
    maxKmh: 1100,
    rfBands: ["SATCOM", "liaison LPI"],
    protocol: "Baykar jet C2",
    remoteId: false,
    payload: "Soute + points d'aile, UCAV jet",
    cues: {
      rf: "LPI / SATCOM, peu d'émissions ISM.",
      visual: "Jet stealthy, entrée d'air dorsale, sans hélice.",
      kinematic: "Subsonique haut, 200 m/s+, profil chasseur.",
      acoustic: "Turboréacteur.",
    },
    notes: "UCAV à réaction. Ne pas confondre avec GJ-11 (aile volante chinoise).",
  }),
  p({
    id: "anka-s",
    name: "Anka-S",
    manufacturer: "TUSAŞ / TAI",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "male",
    role: "isr",
    threat: "critique",
    massKg: 1700,
    enduranceMin: 1440,
    rangeKm: 200,
    ceilingM: 9144,
    cruiseKmh: 204,
    maxKmh: 217,
    rfBands: ["SATCOM", "LOS"],
    protocol: "TAI C2",
    remoteId: false,
    payload: "200 kg ISR, SATCOM natif",
    cues: {
      rf: "SATCOM Anka-S, distinct Baykar.",
      visual: "MALE aile haute, empennage conventionnel (pas V-tail Baykar).",
      kinematic: "ISR 5–9 km, 200 km/h.",
      acoustic: "Turboprop / piston selon variante.",
    },
    notes: "Marqueur visuel: empennage classique, contrairement au V-tail Baykar.",
  }),
  p({
    id: "aksungur",
    name: "Aksungur",
    manufacturer: "TUSAŞ / TAI",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 3300,
    enduranceMin: 2400,
    rangeKm: 6500,
    ceilingM: 12192,
    cruiseKmh: 180,
    maxKmh: 250,
    rfBands: ["SATCOM", "LOS"],
    protocol: "TAI C2 bimoteur",
    remoteId: false,
    payload: "750 kg, bimoteur",
    cues: {
      rf: "SATCOM TAI, endurance extrême.",
      visual: "Bimoteur, empennage TAI, plus massif qu'Anka.",
      kinematic: "MALE long-endurance, 50 m/s.",
      acoustic: "Deux foyers, altitude élevée.",
    },
    notes: "MALE bimoteur TAI. Confusion possible avec Akıncı en EO lointain — comparer empennage.",
  }),
  p({
    id: "kargu-2",
    name: "Kargu-2",
    manufacturer: "STM",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "loitering",
    role: "loitering-munition",
    threat: "critique",
    massKg: 7.1,
    enduranceMin: 30,
    rangeKm: 10,
    ceilingM: 500,
    cruiseKmh: 72,
    maxKmh: 144,
    rfBands: ["2.4 GHz", "bande militaire UHF"],
    protocol: "STM FHSS + visée optronique",
    remoteId: false,
    payload: "Charge militaire, mode rasant autonome",
    cues: {
      rf: "FHSS court rayon, rafales de visée, pas de RID.",
      visual: "Quad militaire, train étroit, ogive avant.",
      kinematic: "Hover puis piqué terminal, Vmax élevée pour un quad.",
      acoustic: "Quad aigu, courte endurance.",
    },
    notes: "Munition rodeuse rotary. Le piqué terminal est un marqueur cinématique critique.",
  }),
  p({
    id: "alpagu",
    name: "Alpagu",
    manufacturer: "STM",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "loitering",
    role: "loitering-munition",
    threat: "critique",
    massKg: 3.7,
    enduranceMin: 15,
    rangeKm: 5,
    ceilingM: 400,
    cruiseKmh: 90,
    maxKmh: 130,
    rfBands: ["UHF", "2.4 GHz"],
    protocol: "STM tube-launch",
    remoteId: false,
    payload: "Charge légère, lancement tube",
    cues: {
      rf: "Courte liaison, lancement depuis tube.",
      visual: "Aile fixe miniature, lancement tube.",
      kinematic: "Vol tendu, endurance 15 min, pas de hover.",
      acoustic: "Hélice miniature aiguë.",
    },
    notes: "Rodeuse aile fixe légère. Distincte de Kargu (rotary).",
  }),
  p({
    id: "togan",
    name: "Togan",
    manufacturer: "STM",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "multirotor",
    role: "isr",
    threat: "elevee",
    massKg: 4.5,
    enduranceMin: 45,
    rangeKm: 10,
    ceilingM: 1000,
    cruiseKmh: 50,
    maxKmh: 70,
    rfBands: ["2.4 GHz", "5.8 GHz"],
    protocol: "STM ISR link",
    remoteId: false,
    payload: "EO/IR, guidage d'essaim Kargu",
    cues: {
      rf: "Liaison ISR STM, parfois coordonnée à un Kargu.",
      visual: "Quad ISR, pas d'ogive de rodeuse.",
      kinematic: "Hover d'observation, 45 min.",
      acoustic: "Quad militaire moyen.",
    },
    notes: "Éclaireur STM. Souvent détecté en paire avec Kargu-2.",
  }),
  p({
    id: "karayel",
    name: "Karayel-SU",
    manufacturer: "Vestel",
    origin: "TR",
    originLabel: "Turquie",
    uasClass: "male",
    role: "isr",
    threat: "elevee",
    massKg: 550,
    enduranceMin: 1200,
    rangeKm: 150,
    ceilingM: 6900,
    cruiseKmh: 150,
    maxKmh: 180,
    rfBands: ["LOS", "SATCOM option"],
    protocol: "Vestel C2",
    remoteId: false,
    payload: "ISR + emport léger",
    cues: {
      rf: "LOS Vestel, moins documenté que Baykar.",
      visual: "MALE aile droite, empennage classique.",
      kinematic: "ISR moyen rayon, 40 m/s.",
      acoustic: "Piston/hélice.",
    },
    notes: "MALE Vestel. Plus rare que TB2 mais dans le mandat turc.",
  }),
  p({
    id: "orlan-10",
    name: "Orlan-10",
    manufacturer: "Special Technology Center",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "elevee",
    massKg: 18,
    enduranceMin: 960,
    rangeKm: 120,
    ceilingM: 5000,
    cruiseKmh: 100,
    maxKmh: 150,
    rfBands: ["430–460 MHz", "900 MHz", "1.2–1.3 GHz"],
    protocol: "Orlan analog/digital video + C2 UHF",
    remoteId: false,
    payload: "EO/IR, relais, 5 kg",
    cues: {
      rf: "UHF 430–460 MHz très caractéristique, vidéo analogique possible.",
      visual: "Aile haute ~3.1 m, fuselage tube, empennage bi-dérive, catapultable.",
      kinematic: "100 km/h, orbites 1–3 km, endurance 10–16 h.",
      acoustic: "Piston deux-temps, audible à basse altitude.",
    },
    notes: "ISR russe le plus répandu. La bande 430–460 MHz est un verrou RF.",
  }),
  p({
    id: "orlan-30",
    name: "Orlan-30",
    manufacturer: "Special Technology Center",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "elevee",
    massKg: 27,
    enduranceMin: 480,
    rangeKm: 120,
    ceilingM: 5000,
    cruiseKmh: 120,
    maxKmh: 170,
    rfBands: ["UHF", "L-band"],
    protocol: "Orlan C2 + désignateur",
    remoteId: false,
    payload: "EO/IR + désignation laser",
    cues: {
      rf: "Famille Orlan, L-band plus fréquent que sur Orlan-10.",
      visual: "Plus grand qu'Orlan-10, même architecture tube.",
      kinematic: "Plus rapide, endurance plus courte.",
      acoustic: "Deux-temps plus grave.",
    },
    notes: "Variante de désignation. Souvent en binôme avec de l'artillerie.",
  }),
  p({
    id: "lancet-3",
    name: "Lancet-3",
    manufacturer: "ZALA Aero",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "loitering",
    role: "loitering-munition",
    threat: "critique",
    massKg: 12,
    enduranceMin: 40,
    rangeKm: 40,
    ceilingM: 5000,
    cruiseKmh: 110,
    maxKmh: 300,
    rfBands: ["900 MHz", "1.2 GHz", "2.4 GHz"],
    protocol: "ZALA FHSS + guidage EO",
    remoteId: false,
    payload: "Charge 3–5 kg, rodeuse",
    cues: {
      rf: "FHSS ZALA, vidéo EO de guidage, pas de RID.",
      visual: "X-wing / double X, fuselage étroit, hélice propulsive.",
      kinematic: "Loiter 110 km/h puis sprint terminal jusqu'à 300 km/h.",
      acoustic: "Hélice électrique, relativement discret jusqu'au piqué.",
    },
    notes: "Munition rodeuse. Le sprint terminal est un marqueur critique d'alerte.",
  }),
  p({
    id: "zala-421-16e",
    name: "ZALA 421-16E",
    manufacturer: "ZALA Aero",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "elevee",
    massKg: 7.5,
    enduranceMin: 240,
    rangeKm: 50,
    ceilingM: 3600,
    cruiseKmh: 90,
    maxKmh: 130,
    rfBands: ["900 MHz", "2.4 GHz"],
    protocol: "ZALA ISR",
    remoteId: false,
    payload: "EO/IR 1.5 kg",
    cues: {
      rf: "ZALA ISR, 900 MHz fréquent.",
      visual: "Aile fixe petite, catapulte / main.",
      kinematic: "ISR 4 h, 90 km/h.",
      acoustic: "Électrique, discret.",
    },
    notes: "Éclaireur ZALA, souvent en amont d'un Lancet.",
  }),
  p({
    id: "orion",
    name: "Orion / Inokhodets",
    manufacturer: "Kronshtadt",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "male",
    role: "strike",
    threat: "critique",
    massKg: 1150,
    enduranceMin: 1440,
    rangeKm: 250,
    ceilingM: 7500,
    cruiseKmh: 200,
    maxKmh: 200,
    rfBands: ["LOS", "SATCOM"],
    protocol: "Kronshtadt C2",
    remoteId: false,
    payload: "250 kg, UCAV MALE",
    cues: {
      rf: "LOS/SATCOM MALE russe, hors ISM.",
      visual: "MALE ~16 m, empennage en V, boule optronique.",
      kinematic: "200 km/h, 24 h, altitude 5–7 km.",
      acoustic: "Hélice, haute altitude.",
    },
    notes: "MALE russe. Silhouette proche des MALE chinois/turcs — départager par RF et SATCOM.",
  }),
  p({
    id: "forpost-r",
    name: "Forpost-R",
    manufacturer: "URALCIVILAVIATION / IAI licence",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "male",
    role: "isr",
    threat: "elevee",
    massKg: 500,
    enduranceMin: 1080,
    rangeKm: 250,
    ceilingM: 5800,
    cruiseKmh: 150,
    maxKmh: 200,
    rfBands: ["LOS", "SATCOM"],
    protocol: "Forpost C2",
    remoteId: false,
    payload: "ISR 60 kg",
    cues: {
      rf: "LOS MALE, architecture Searcher russifiée.",
      visual: "MALE train tricycle, empennage double, ~8.5 m.",
      kinematic: "ISR 150 km/h, 18 h.",
      acoustic: "Piston, audible plus bas que les gros MALE.",
    },
    notes: "Dérivé Searcher. Identification visuelle: double dérive et train fixe.",
  }),
  p({
    id: "eleron-3",
    name: "Eleron-3SV",
    manufacturer: "ENICS",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "elevee",
    massKg: 4.3,
    enduranceMin: 120,
    rangeKm: 50,
    ceilingM: 4000,
    cruiseKmh: 70,
    maxKmh: 130,
    rfBands: ["430 MHz", "900 MHz"],
    protocol: "ENICS C2",
    remoteId: false,
    payload: "EO 1 kg",
    cues: {
      rf: "UHF 430 MHz proche Orlan mais protocole ENICS.",
      visual: "Aile delta / trapèze petite, lancement main.",
      kinematic: "70 km/h, 2 h.",
      acoustic: "Électrique léger.",
    },
    notes: "ISR tactique. Distinguer d'Orlan par la taille et l'absence de fuselage tube long.",
  }),
  p({
    id: "supercam-s350",
    name: "SuperCam S350",
    manufacturer: "Unmanned Systems",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "elevee",
    massKg: 15,
    enduranceMin: 240,
    rangeKm: 70,
    ceilingM: 5000,
    cruiseKmh: 80,
    maxKmh: 120,
    rfBands: ["900 MHz", "2.4 GHz"],
    protocol: "SuperCam digital",
    remoteId: false,
    payload: "EO/IR",
    cues: {
      rf: "900 MHz digital, pas analogique Orlan.",
      visual: "Aile haute, fuselage pod, empennage en V.",
      kinematic: "80 km/h, 4 h.",
      acoustic: "Électrique / petit piston selon version.",
    },
    notes: "ISR cartographique aussi utilisé en reconnaissance.",
  }),
  p({
    id: "geran-2",
    name: "Geran-2",
    manufacturer: "Alabuga / Geran",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "loitering",
    role: "loitering-munition",
    threat: "critique",
    massKg: 200,
    enduranceMin: 600,
    rangeKm: 2000,
    ceilingM: 4000,
    cruiseKmh: 170,
    maxKmh: 185,
    rfBands: ["GNSS", "occasionnel C2 SAT/cellulaire"],
    protocol: "INS/GNSS + C2 intermittent",
    remoteId: false,
    payload: "Charge ~50 kg, delta",
    cues: {
      rf: "Peu de C2 continu — GNSS/INS, parfois module cellulaire. Radar + acoustique prioritaires.",
      visual: "Aile delta, moteur MD-550 en poussée, ~3.5 m.",
      kinematic: "170 km/h constant, altitude 50–2500 m, pas d'orbite ISR.",
      acoustic: "Deux-temps très bruyant, signature acoustique longue distance.",
    },
    notes: "Munition longue portée. Identification souvent acoustique + radar avant la RF.",
  }),
  p({
    id: "kub-bla",
    name: "KUB-BLA",
    manufacturer: "ZALA Aero",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "loitering",
    role: "loitering-munition",
    threat: "critique",
    massKg: 7,
    enduranceMin: 30,
    rangeKm: 40,
    ceilingM: 2500,
    cruiseKmh: 80,
    maxKmh: 130,
    rfBands: ["900 MHz", "2.4 GHz"],
    protocol: "ZALA KUB",
    remoteId: false,
    payload: "Charge 3 kg, aile delta",
    cues: {
      rf: "ZALA, courte portée.",
      visual: "Delta compacte, pas de X-wing Lancet.",
      kinematic: "Loiter lent puis piqué.",
      acoustic: "Électrique, plus discret que Geran.",
    },
    notes: "Rodeuse delta ZALA. Ne pas confondre avec Lancet (X-wing) ni Geran (gros delta bruyant).",
  }),
  p({
    id: "s70-okhotnik",
    name: "S-70 Okhotnik",
    manufacturer: "Sukhoi",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "ucav",
    role: "strike",
    threat: "critique",
    massKg: 20000,
    enduranceMin: 360,
    rangeKm: 6000,
    ceilingM: 14000,
    cruiseKmh: 790,
    maxKmh: 1000,
    rfBands: ["liaison LPI", "SATCOM"],
    protocol: "Sukhoi LPI / MUM-T",
    remoteId: false,
    payload: "Soute interne, UCAV lourd",
    cues: {
      rf: "LPI, fusion radar 3D obligatoire.",
      visual: "Aile volante lourde, plus grande que GJ-11.",
      kinematic: "Jet subsonique, 200 m/s+.",
      acoustic: "Turboréacteur.",
    },
    notes: "UCAV lourd. Rare ; toute piste jet furtive doit être corrélée MALE vs UCAV.",
  }),
  p({
    id: "granat-4",
    name: "Granat-4",
    manufacturer: "Izhmash",
    origin: "RU",
    originLabel: "Russie",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "moderee",
    massKg: 4.2,
    enduranceMin: 360,
    rangeKm: 30,
    ceilingM: 3500,
    cruiseKmh: 90,
    maxKmh: 120,
    rfBands: ["430 MHz", "900 MHz"],
    protocol: "Granat C2",
    remoteId: false,
    payload: "EO 1 kg",
    cues: {
      rf: "UHF tactique russe.",
      visual: "Aile fixe petite, lancement main / catapulte.",
      kinematic: "90 km/h, 6 h.",
      acoustic: "Électrique.",
    },
    notes: "ISR d'unité. Mandat RU confirmé par bande UHF et protocole Granat.",
  }),
  ...EXTRA_PLATFORMS,
];

export const OUT_OF_MANDATE: Platform[] = [
  p({
    id: "adsb-uav",
    name: "UAS ADS-B (B6)",
    manufacturer: "Inconnu",
    origin: "XX",
    originLabel: "Hors mandat",
    uasClass: "fixed-wing",
    role: "isr",
    threat: "elevee",
    massKg: 25,
    enduranceMin: 180,
    rangeKm: 80,
    ceilingM: 3500,
    cruiseKmh: 120,
    maxKmh: 180,
    rfBands: ["1090ES"],
    protocol: "ADS-B emitter category B6",
    remoteId: false,
    payload: "UAS avec transpondeur 1090ES live",
    cues: {
      rf: "Squitter DF17, catégorie B6 UAV. Pas un airliner.",
      visual: "Aile fixe ou VTOL selon type ICAO.",
      kinematic: "Plus lent qu'un IFR civil, plafond bas.",
      acoustic: "Selon propulsion — non déterminé par 1090.",
    },
    notes: "Contact 1090ES réel classé UAV (catégorie B6). Hors mandat tant que l'origine n'est pas CN/TR/RU/IR.",
  }),
  p({
    id: "skydio-x10",
    name: "X10",
    manufacturer: "Skydio",
    origin: "XX",
    originLabel: "Hors mandat",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "moderee",
    massKg: 2.2,
    enduranceMin: 40,
    rangeKm: 10,
    ceilingM: 3500,
    cruiseKmh: 50,
    maxKmh: 72,
    rfBands: ["2.4 GHz", "5.8 GHz"],
    protocol: "SkydioLink",
    remoteId: true,
    payload: "EO/IR",
    cues: {
      rf: "SkydioLink, RID ASTM.",
      visual: "Quad US, capteurs d'évitement visibles.",
      kinematic: "Hover autonome.",
      acoustic: "Quad.",
    },
    notes: "Origine États-Unis — hors mandat CN/TR/RU.",
  }),
  p({
    id: "parrot-anafi",
    name: "Anafi USA",
    manufacturer: "Parrot",
    origin: "XX",
    originLabel: "Hors mandat",
    uasClass: "multirotor",
    role: "enterprise-isr",
    threat: "faible",
    massKg: 0.5,
    enduranceMin: 32,
    rangeKm: 5,
    ceilingM: 4000,
    cruiseKmh: 40,
    maxKmh: 55,
    rfBands: ["2.4 GHz", "5.8 GHz"],
    protocol: "Parrot Skycontroller",
    remoteId: true,
    payload: "EO 4K + IR",
    cues: {
      rf: "Parrot, RID.",
      visual: "Quad plat, nacelle 180°.",
      kinematic: "Hover léger.",
      acoustic: "Quad aigu.",
    },
    notes: "Origine France — hors mandat.",
  }),
  p({
    id: "f16-block50",
    name: "F-16C Block 50+",
    manufacturer: "Lockheed Martin / TAI",
    origin: "XX",
    originLabel: "Hors mandat",
    uasClass: "chasse",
    role: "fighter",
    threat: "critique",
    massKg: 8900,
    enduranceMin: 120,
    rangeKm: 4200,
    ceilingM: 15240,
    cruiseKmh: 900,
    maxKmh: 2120,
    rfBands: ["IFF Mode 4/5", "radar APG"],
    protocol: "IFF OTAN",
    remoteId: false,
    payload: "Chasse multirôle",
    cues: {
      rf: "IFF OTAN, pas de datalink PLAAF/VKS/TAI MMU.",
      visual: "Mono-réacteur, entrée ventrale, empennage unique.",
      kinematic: "Mach 2, 9–12 km.",
      acoustic: "F110 / F100, jet.",
    },
    notes: "Conception États-Unis. Même opéré par la Turquie : hors mandat CN/TR/RU.",
  }),
];

export const PLATFORM_BY_ID: Record<string, Platform> = Object.fromEntries(
  [...PLATFORMS, ...OUT_OF_MANDATE, ...FRIEND_PLATFORMS].map((x) => [x.id, x]),
);

export const MANDATE_ORIGINS: Origin[] = ["CN", "TR", "RU", "IR"];

export function platformsByOrigin(origin: Origin): Platform[] {
  return PLATFORMS.filter((x) => x.origin === origin);
}

export function threatRank(t: Threat): number {
  return { faible: 1, moderee: 2, elevee: 3, critique: 4 }[t];
}

export function classLabel(c: UasClass): string {
  switch (c) {
    case "multirotor":
      return "Multirotor";
    case "fixed-wing":
      return "Aile fixe";
    case "vtol":
      return "VTOL";
    case "loitering":
      return "Munition rodeuse";
    case "male":
      return "MALE";
    case "ucav":
      return "UCAV";
    case "chasse":
      return "Chasse";
  }
}

export function roleLabel(r: Platform["role"]): string {
  switch (r) {
    case "consumer":
      return "Grand public";
    case "enterprise-isr":
      return "ISR civil";
    case "agriculture":
      return "Agricole";
    case "logistics":
      return "Fret";
    case "isr":
      return "ISR";
    case "strike":
      return "Frappe / UCAV";
    case "loitering-munition":
      return "Munition rodeuse";
    case "mothership":
      return "Porte-drones";
    case "fighter":
      return "Chasse";
    case "trainer":
      return "Entraînement / léger";
    case "rotary":
      return "Voilure tournante";
    case "airliner":
      return "Ligne ASECNA";
    case "transport":
      return "Transport";
  }
}

export function threatLabel(t: Threat): string {
  switch (t) {
    case "faible":
      return "Faible";
    case "moderee":
      return "Modérée";
    case "elevee":
      return "Élevée";
    case "critique":
      return "Critique";
  }
}

export function originLabel(o: Origin): string {
  switch (o) {
    case "CN":
      return "Chine";
    case "TR":
      return "Turquie";
    case "RU":
      return "Russie";
    case "IR":
      return "Iran";
    case "XX":
      return "Hors mandat";
  }
}

export type CatalogFamily = "commercial" | "uas-mil" | "chasse" | "ami";

export function familyOf(p: Platform): CatalogFamily {
  if (p.friendKind) return "ami";
  if (p.uasClass === "chasse") return "chasse";
  if (
    p.role === "consumer" ||
    p.role === "enterprise-isr" ||
    p.role === "agriculture" ||
    p.role === "logistics"
  ) {
    return "commercial";
  }
  return "uas-mil";
}

export function familyLabel(f: CatalogFamily): string {
  switch (f) {
    case "commercial":
      return "Commercial";
    case "uas-mil":
      return "UAS militaire";
    case "chasse":
      return "Chasse";
    case "ami":
      return "Amis FATL / ASECNA";
  }
}

export function idStateLabel(s: import("./types").IdState): string {
  switch (s) {
    case "detecte":
      return "Détecté";
    case "classification":
      return "Classification";
    case "candidat":
      return "Candidat";
    case "confirme":
      return "Confirmé";
    case "hors-mandat":
      return "Hors mandat";
    case "perdu":
      return "Perdu";
  }
}

export function sensorLabel(k: import("./types").SensorKind): string {
  switch (k) {
    case "rf":
      return "RF";
    case "radar":
      return "Radar 3D";
    case "eoir":
      return "EO/IR";
    case "acoustic":
      return "Acoustique";
  }
}
