/** Fiches amis — FATL et trafic ASECNA. Hors pickTruePlatform (mandat hostile). */

import type { FriendKind, Origin, Platform, Role, Threat, UasClass } from "./types";

const ORIGIN_LABEL: Record<Origin, string> = {
  CN: "Chine",
  TR: "Turquie",
  RU: "Russie",
  IR: "Iran",
  XX: "Hors mandat",
};

function f(o: {
  id: string;
  name: string;
  mfr: string;
  origin: Origin;
  kind: FriendKind;
  cls: UasClass;
  role: Role;
  kg: number;
  min: number;
  km: number;
  ceil: number;
  cruise: number;
  vmax: number;
  proto: string;
  payload: string;
  rf: string;
  vis: string;
  kin: string;
  ac: string;
  notes: string;
  bands?: string[];
  threat?: Threat;
}): Platform {
  return {
    id: o.id,
    name: o.name,
    manufacturer: o.mfr,
    origin: o.origin,
    originLabel: ORIGIN_LABEL[o.origin],
    uasClass: o.cls,
    role: o.role,
    threat: o.threat ?? "faible",
    massKg: o.kg,
    enduranceMin: o.min,
    rangeKm: o.km,
    ceilingM: o.ceil,
    cruiseKmh: o.cruise,
    maxKmh: o.vmax,
    rfBands: o.bands ?? ["IFF Mode 4", "Mode 3/A", "UHF/VHF"],
    protocol: o.proto,
    remoteId: o.kind === "asecna",
    payload: o.payload,
    cues: { rf: o.rf, visual: o.vis, kinematic: o.kin, acoustic: o.ac },
    notes: o.notes,
    friendKind: o.kind,
  };
}

export const FRIEND_PLATFORMS: Platform[] = [
  f({
    id: "fatl-mi24",
    name: "Mi-24P",
    mfr: "Mil / Rostvertol",
    origin: "RU",
    kind: "fatl",
    cls: "vtol",
    role: "rotary",
    kg: 11200,
    min: 180,
    km: 450,
    ceil: 4500,
    cruise: 215,
    vmax: 335,
    proto: "IFF FATL Mode 4 + UHF",
    payload: "Canon + roquettes · appui-feu FATL",
    bands: ["IFF Mode 4", "IFF Mode 3/A", "UHF tactique", "VHF"],
    rf: "IFF Mode 4 crypto FATL + squawk 3/A. Pas de C2 ISM.",
    vis: "Hind, nez canon, ailes stub, rotor 5 pales.",
    kin: "80–220 km/h, 50–1500 m, patrouille autour d'une base.",
    ac: "Turbine TV3-117, BPF rotor ~5 Hz.",
    notes:
      "Hélicoptère d'attaque FATL. Origine constructeur Russie — affiliation amie Tchad. Effecteur C-UAS interdit.",
  }),
  f({
    id: "fatl-mi17",
    name: "Mi-17",
    mfr: "Kazán / Mil",
    origin: "RU",
    kind: "fatl",
    cls: "vtol",
    role: "rotary",
    kg: 11100,
    min: 200,
    km: 465,
    ceil: 6000,
    cruise: 220,
    vmax: 250,
    proto: "IFF FATL Mode 4 + UHF",
    payload: "Transport troupes / CASEVAC",
    rf: "IFF Mode 4 + 3/A, UHF. Pas de protocole drone.",
    vis: "Hip, cabine large, rotor 5 pales, treuil.",
    kin: "Patrouille / liaison base, 100–800 m.",
    ac: "Rotor lourd, signature grave.",
    notes: "Transport FATL. Affiliation amie, même si la cellule est d'origine russe.",
  }),
  f({
    id: "fatl-c130",
    name: "C-130H",
    mfr: "Lockheed Martin",
    origin: "XX",
    kind: "fatl",
    cls: "fixed-wing",
    role: "transport",
    kg: 34300,
    min: 360,
    km: 3800,
    ceil: 10000,
    cruise: 540,
    vmax: 590,
    proto: "IFF Mode 4 + Mode S + ADS-B 1090",
    payload: "Fret / parachutage",
    bands: ["IFF Mode 4", "IFF Mode S", "ADS-B 1090", "HF/UHF"],
    rf: "Mode 4 FATL + Mode S + ADS-B. Transpondeur mil/civ visible ASECNA.",
    vis: "Hercules, aile haute, 4 turboprop.",
    kin: "FL180–FL250, 500 km/h, liaisons FTTJ–Abéché–Faya.",
    ac: "Quatre T56, grave.",
    notes: "Transport FATL. Hors mandat constructeur (US) — couche amis, pas XX hostile.",
  }),
  f({
    id: "fatl-an26",
    name: "An-26",
    mfr: "Antonov",
    origin: "RU",
    kind: "fatl",
    cls: "fixed-wing",
    role: "transport",
    kg: 15020,
    min: 220,
    km: 1100,
    ceil: 7500,
    cruise: 430,
    vmax: 540,
    proto: "IFF Mode 4 FATL",
    payload: "Fret tactique",
    rf: "IFF Mode 4 + 3/A, VHF. Pas d'OcuSync.",
    vis: "Curl, aile haute, rampe arrière, 2 turboprop.",
    kin: "FL120–FL180, liaisons intérieures.",
    ac: "Deux AI-24.",
    notes: "Fret FATL. Origine RU, affiliation Tchad.",
  }),
  f({
    id: "fatl-su25",
    name: "Su-25",
    mfr: "Sukhoi",
    origin: "RU",
    kind: "fatl",
    cls: "chasse",
    role: "fighter",
    kg: 10760,
    min: 110,
    km: 750,
    ceil: 7000,
    cruise: 700,
    vmax: 950,
    proto: "IFF FATL Mode 4 + UHF",
    payload: "Appui-feu, 4 t",
    bands: ["IFF Mode 4", "IFF Mode 3/A", "UHF", "radar télémétrique"],
    rf: "IFF Mode 4 FATL, pas de datalink VKS. Discriminant vs Frogfoot hostile.",
    vis: "Frogfoot, aile droite, biréacteur trapu.",
    kin: "Rasant 50–3000 m, 600–850 km/h.",
    ac: "R-95 ×2, très bruyant bas.",
    notes:
      "Appui-feu FATL. Même type que le Su-25SM du mandat RU — c'est le Mode 4 FATL qui fait l'ami, pas la silhouette.",
  }),
  f({
    id: "fatl-pc7",
    name: "PC-7",
    mfr: "Pilatus",
    origin: "XX",
    kind: "fatl",
    cls: "fixed-wing",
    role: "trainer",
    kg: 1900,
    min: 240,
    km: 1200,
    ceil: 8000,
    cruise: 330,
    vmax: 500,
    proto: "IFF Mode 4 + Mode 3/A + VHF",
    payload: "Entraînement / COIN léger",
    rf: "IFF, VHF. Pas de C2 drone.",
    vis: "Turbo Trainer, tandem, hélice, aile basse.",
    kin: "200–400 km/h, 500–4000 m, tours FTTJ.",
    ac: "PT6A, turboprop.",
    notes: "École FATL. Hors mandat constructeur (CH).",
  }),
  f({
    id: "fatl-ch4",
    name: "CH-4B",
    mfr: "CASC / CAAA",
    origin: "CN",
    kind: "fatl",
    cls: "male",
    role: "isr",
    kg: 1330,
    min: 2040,
    km: 3500,
    ceil: 7200,
    cruise: 180,
    vmax: 235,
    proto: "Liaison SATCOM FATL + IFF Mode 4",
    payload: "ISR / frappe FATL",
    bands: ["SATCOM", "IFF Mode 4", "IFF Mode 3/A", "C-band LOS"],
    rf: "IFF Mode 4 FATL + SATCOM national. Même famille Rainbow que le mandat CN — affiliation Tchad.",
    vis: "MALE aile haute, empennage en V, train tricycle.",
    kin: "Loiter 150–180 km/h, 4000–6000 m, box FTTJ / Abéché.",
    ac: "Mono turboprop discret.",
    notes:
      "UAS FATL d'origine chinoise. Origine CN ≠ hostile : le Mode 4 FATL prime. Effecteur interdit.",
  }),
  f({
    id: "asecna-a320",
    name: "A320",
    mfr: "Airbus",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 42000,
    min: 360,
    km: 6100,
    ceil: 12000,
    cruise: 840,
    vmax: 890,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Pax ~180",
    bands: ["ADS-B 1090", "Mode S", "VHF COM"],
    rf: "ADS-B squitter 1090, Mode S. Flux ASECNA FIR FTTT — pas un UAS.",
    vis: "Biréacteur couloir unique, aile basse.",
    kin: "FL310–FL370, 800 km/h, voies UA/UB.",
    ac: "CFM56 / PW1100, jet de ligne.",
    notes: "Trafic IFR ASECNA (ETH, KP, MS…). Identification ADS-B, pas C-UAS.",
  }),
  f({
    id: "asecna-b737",
    name: "737-800",
    mfr: "Boeing",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 41400,
    min: 320,
    km: 5400,
    ceil: 12500,
    cruise: 850,
    vmax: 876,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Pax ~160",
    rf: "ADS-B 1090, Mode S. Corrélation plan de vol ASECNA.",
    vis: "737, entrée moteur sous aile, empennage unique.",
    kin: "FL330–FL370, voies trans-sahéliennes.",
    ac: "CFM56-7B.",
    notes: "Ligne régulière / cargo ASECNA. Ami civil.",
  }),
  f({
    id: "asecna-atr72",
    name: "ATR 72",
    mfr: "ATR",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 13300,
    min: 300,
    km: 1500,
    ceil: 7600,
    cruise: 510,
    vmax: 560,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Pax ~70 · régional",
    rf: "ADS-B, Mode S, VHF. Liaisons régionales FIR FTTT.",
    vis: "Biturboprop, aile haute, empennage en T.",
    kin: "FL170–FL220, 500 km/h, N'Djamena–Moundou–Sarh.",
    ac: "PW127, turboprop.",
    notes: "Régional ASECNA / compagnies de la zone.",
  }),
  f({
    id: "asecna-e190",
    name: "E190",
    mfr: "Embraer",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 28000,
    min: 300,
    km: 4500,
    ceil: 12500,
    cruise: 820,
    vmax: 870,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Pax ~100",
    rf: "ADS-B 1090. Plan de vol ASECNA.",
    vis: "E-Jet, biréacteur arrière, aile basse.",
    kin: "FL350, liaisons régionales longues.",
    ac: "CF34.",
    notes: "Trafic ASECNA moyen-courrier.",
  }),
  f({
    id: "asecna-wide",
    name: "Widebody",
    mfr: "Airbus / Boeing",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 180000,
    min: 720,
    km: 12000,
    ceil: 13100,
    cruise: 900,
    vmax: 945,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Pax long-courrier",
    bands: ["ADS-B 1090", "Mode S", "VHF COM"],
    rf: "Squitter DF17 1090ES. Long-courrier sur voies UA/UM.",
    vis: "Biréacteur / quadriréacteur large fuselage.",
    kin: "FL330–FL410, 880–920 km/h.",
    ac: "Turboréacteur high-bypass.",
    notes: "A330 / A350 / B777 / B787 — flux 1090ES live, ami civil ASECNA.",
  }),
  f({
    id: "asecna-biz",
    name: "Bizjet",
    mfr: "Gulfstream / Dassault / Cessna",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 12000,
    min: 360,
    km: 5000,
    ceil: 15500,
    cruise: 850,
    vmax: 950,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Affaires / VIP",
    rf: "ADS-B 1090. Plan de vol IFR.",
    vis: "Biréacteur d'affaires, aile basse.",
    kin: "FL400+, 800 km/h.",
    ac: "Biréacteur compact.",
    notes: "Aviation d'affaires entendue en 1090ES. Ami civil.",
  }),
  f({
    id: "asecna-unk",
    name: "IFR 1090ES",
    mfr: "Inconnu",
    origin: "XX",
    kind: "asecna",
    cls: "fixed-wing",
    role: "airliner",
    kg: 20000,
    min: 180,
    km: 2000,
    ceil: 12000,
    cruise: 700,
    vmax: 900,
    proto: "ADS-B 1090ES + Mode S",
    payload: "Trafic IFR non typé",
    rf: "Squitter 1090ES. Type ICAO non corrélé.",
    vis: "Contact Mode S sans fiche type.",
    kin: "Cinématique IFR.",
    ac: "Signature jet / turboprop selon régime.",
    notes: "Contact 1090ES live sans type ICAO. Affiliation civile par défaut, pas un UAS.",
  }),
];

export const FRIEND_BY_ID: Record<string, Platform> = Object.fromEntries(
  FRIEND_PLATFORMS.map((p) => [p.id, p]),
);

export const FATL_PLATFORMS = FRIEND_PLATFORMS.filter((p) => p.friendKind === "fatl");
const LIVE_ONLY = new Set(["asecna-wide", "asecna-biz", "asecna-unk"]);
export const ASECNA_PLATFORMS = FRIEND_PLATFORMS.filter(
  (p) => p.friendKind === "asecna" && !LIVE_ONLY.has(p.id),
);
