import type { Origin, Platform, Role, Threat, UasClass } from "./types";

const ORIGIN_LABEL: Record<Origin, string> = {
  CN: "Chine",
  TR: "Turquie",
  RU: "Russie",
  IR: "Iran",
  XX: "Hors mandat",
};

function m(o: {
  id: string;
  name: string;
  mfr: string;
  origin: Origin;
  cls?: UasClass;
  role?: Role;
  threat?: Threat;
  kg: number;
  min: number;
  km: number;
  ceil: number;
  cruise: number;
  vmax: number;
  bands?: string[];
  proto: string;
  rid?: boolean;
  payload: string;
  rf: string;
  vis: string;
  kin: string;
  ac: string;
  notes: string;
}): Platform {
  const cls = o.cls ?? "multirotor";
  const role = o.role ?? "consumer";
  return {
    id: o.id,
    name: o.name,
    manufacturer: o.mfr,
    origin: o.origin,
    originLabel: ORIGIN_LABEL[o.origin],
    uasClass: cls,
    role,
    threat: o.threat ?? (cls === "chasse" ? "critique" : role === "consumer" ? "faible" : "moderee"),
    massKg: o.kg,
    enduranceMin: o.min,
    rangeKm: o.km,
    ceilingM: o.ceil,
    cruiseKmh: o.cruise,
    maxKmh: o.vmax,
    rfBands: o.bands ?? (cls === "chasse" ? ["IFF Mode 3/C/S", "radar aéroporté"] : ["2.400–2.483 GHz", "5.725–5.850 GHz"]),
    protocol: o.proto,
    remoteId: o.rid ?? (cls !== "chasse" && role === "consumer"),
    payload: o.payload,
    cues: { rf: o.rf, visual: o.vis, kinematic: o.kin, acoustic: o.ac },
    notes: o.notes,
  };
}

export const EXTRA_PLATFORMS: Platform[] = [
  // —— Drones commerciaux Chine ——
  m({ id: "dji-mini-2-se", name: "Mini 2 SE", mfr: "DJI", origin: "CN", kg: 0.246, min: 31, km: 10, ceil: 4000, cruise: 36, vmax: 54, proto: "OcuSync 2.0", payload: "Caméra 2.7K", rf: "OcuSync 2, ISM 2.4/5.8, RID selon firmware.", vis: "Quad pliable ultra-léger, bras Mini.", kin: "Hover, <15 m/s.", ac: "Quad aigu léger.", notes: "Grand public DJI sous 250 g." }),
  m({ id: "dji-mini-3", name: "Mini 3", mfr: "DJI", origin: "CN", kg: 0.248, min: 38, km: 12, ceil: 4000, cruise: 36, vmax: 58, proto: "OcuSync 3", payload: "Caméra 4K", rf: "OcuSync 3, RID.", vis: "Bras Mini 3, nacelle verticale.", kin: "Hover, endurance 38 min.", ac: "Quad léger.", notes: "Série Mini commerciale." }),
  m({ id: "dji-mini-3-pro", name: "Mini 3 Pro", mfr: "DJI", origin: "CN", kg: 0.249, min: 34, km: 12, ceil: 4000, cruise: 36, vmax: 58, proto: "OcuSync 3", payload: "Caméra 4K HDR, détection obstacles", rf: "OcuSync 3, RID.", vis: "Mini 3 Pro, capteurs avant.", kin: "Hover, 16 m/s Cine/N.", ac: "Quad léger.", notes: "Mini Pro, très fréquent en ville." }),
  m({ id: "dji-air-2s", name: "Air 2S", mfr: "DJI", origin: "CN", kg: 0.595, min: 31, km: 12, ceil: 5000, cruise: 54, vmax: 68, proto: "OcuSync 3.0", payload: "Caméra 5.4K 1 pouce", rf: "OcuSync 3, RID.", vis: "Quad Air, capteur 1 pouce.", kin: "15 m/s, 31 min.", ac: "Quad médium.", notes: "Série Air commerciale." }),
  m({ id: "dji-air-3", name: "Air 3", mfr: "DJI", origin: "CN", kg: 0.72, min: 46, km: 20, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 4", payload: "Double caméra 24/70 mm", rf: "OcuSync 4, RID.", vis: "Bi-capteur, châssis Air 3.", kin: "46 min, 21 m/s.", ac: "Quad médium.", notes: "Air 3 grand public." }),
  m({ id: "dji-air-3s", name: "Air 3S", mfr: "DJI", origin: "CN", kg: 0.724, min: 45, km: 20, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 4", payload: "Caméra 1 pouce + télé", rf: "OcuSync 4, RID.", vis: "Air 3S, lidar avant.", kin: "Hover longue endurance.", ac: "Quad médium.", notes: "Évolution Air 3." }),
  m({ id: "dji-avata", name: "Avata", mfr: "DJI", origin: "CN", kg: 0.41, min: 18, km: 10, ceil: 3000, cruise: 54, vmax: 97, proto: "OcuSync 3 FPV", payload: "Caméra 4K FPV, cage", rf: "OcuSync FPV, faible latence.", vis: "Cinewhoop cage, hélice ducted.", kin: "FPV jusqu'à 27 m/s, pas d'hover long.", ac: "Quad FPV aigu.", notes: "FPV commercial DJI." }),
  m({ id: "dji-avata-2", name: "Avata 2", mfr: "DJI", origin: "CN", kg: 0.377, min: 23, km: 13, ceil: 3000, cruise: 54, vmax: 97, proto: "OcuSync 4 FPV", payload: "4K FPV, Goggles 3", rf: "OcuSync 4 FPV.", vis: "Cage Avata 2, plus compact.", kin: "FPV 27 m/s.", ac: "Quad FPV.", notes: "FPV grand public 2e gén." }),
  m({ id: "dji-fpv", name: "DJI FPV", mfr: "DJI", origin: "CN", kg: 0.795, min: 20, km: 10, ceil: 5000, cruise: 72, vmax: 140, proto: "OcuSync FPV", payload: "Caméra FPV 4K", rf: "OcuSync FPV dédié.", vis: "Châssis FPV non cage, ailes latérales.", kin: "Jusqu'à 140 km/h, profil course.", ac: "Quad FPV bruyant.", notes: "Course FPV DJI." }),
  m({ id: "dji-neo", name: "Neo", mfr: "DJI", origin: "CN", kg: 0.135, min: 18, km: 0.5, ceil: 500, cruise: 28, vmax: 43, proto: "Wi-Fi / OcuSync light", payload: "Caméra 4K selfie", rf: "Wi-Fi 2.4/5.8, courte portée.", vis: "Tiny quad palm, hélices gardées.", kin: "Hover selfie, <50 m typique.", ac: "Très aigu, faible RCS.", notes: "Nano commercial. Détection urbaine difficile." }),
  m({ id: "dji-phantom-4-pro", name: "Phantom 4 Pro V2", mfr: "DJI", origin: "CN", kg: 1.388, min: 30, km: 7, ceil: 6000, cruise: 50, vmax: 72, proto: "OcuSync / Lightbridge", payload: "Caméra 20 MP 1 pouce", rf: "OcuSync Phantom, RID selon région.", vis: "Quad blanc jambes, icône historique DJI.", kin: "Hover stable, 20 m/s.", ac: "Quad médium grave.", notes: "Phantom encore en circulation." }),
  m({ id: "dji-mavic-2-pro", name: "Mavic 2 Pro", mfr: "DJI", origin: "CN", kg: 0.907, min: 31, km: 8, ceil: 6000, cruise: 50, vmax: 72, proto: "OcuSync 2.0", payload: "Hasselblad 20 MP", rf: "OcuSync 2.", vis: "Mavic 2, nacelle Hasselblad.", kin: "31 min, 72 km/h.", ac: "Quad médium.", notes: "Ancienne référence photo." }),
  m({ id: "dji-mavic-3-classic", name: "Mavic 3 Classic", mfr: "DJI", origin: "CN", kg: 0.895, min: 46, km: 15, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 3", payload: "Hasselblad 4/3", rf: "OcuSync 3, RID.", vis: "Mavic 3 sans téléobjectif.", kin: "46 min.", ac: "Quad médium.", notes: "Mavic 3 civil." }),
  m({ id: "dji-mavic-3-pro", name: "Mavic 3 Pro", mfr: "DJI", origin: "CN", kg: 0.958, min: 43, km: 15, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 3", payload: "Triple caméra Hasselblad", rf: "OcuSync 3, RID.", vis: "Triple nacelle distinctive.", kin: "43 min.", ac: "Quad médium.", notes: "Haut de gamme photo DJI." }),
  m({ id: "dji-mavic-3e", name: "Mavic 3E", mfr: "DJI", origin: "CN", role: "enterprise-isr", kg: 0.915, min: 45, km: 15, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 3 Enterprise", payload: "EO 4/3 + obturateur mécanique", rf: "OcuSync 3E, RID.", vis: "Mavic 3 Enterprise, sans IR.", kin: "ISR rasant.", ac: "Quad médium.", notes: "Enterprise carto." }),
  m({ id: "dji-inspire-2", name: "Inspire 2", mfr: "DJI", origin: "CN", role: "enterprise-isr", kg: 3.44, min: 27, km: 7, ceil: 5000, cruise: 58, vmax: 94, proto: "Lightbridge 2", payload: "Nacelle Zenmuse X7/X5S", rf: "Lightbridge 2, distinct d'OcuSync.", vis: "Quad transformable, trains relevables.", kin: "94 km/h, cinéma.", ac: "Quad puissant.", notes: "Cinéma / insp. ancien mais encore vu." }),
  m({ id: "dji-inspire-3", name: "Inspire 3", mfr: "DJI", origin: "CN", role: "enterprise-isr", kg: 3.99, min: 28, km: 15, ceil: 6800, cruise: 75, vmax: 94, proto: "OcuSync 3 Pro", payload: "Caméra 8K plein format", rf: "OcuSync 3 Pro.", vis: "Inspire 3, trains + RTK option.", kin: "Cinéma rapide.", ac: "Quad lourd.", notes: "Cinéma haut de gamme." }),
  m({ id: "dji-matrice-4e", name: "Matrice 4E", mfr: "DJI", origin: "CN", role: "enterprise-isr", kg: 1.22, min: 49, km: 25, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 4 Enterprise", payload: "EO carto + laser", rf: "OcuSync 4E.", vis: "Compact enterprise, nacelle multi.", kin: "ISR 49 min.", ac: "Quad médium.", notes: "Nouvelle série Matrice 4." }),
  m({ id: "dji-matrice-4t", name: "Matrice 4T", mfr: "DJI", origin: "CN", role: "enterprise-isr", kg: 1.22, min: 49, km: 25, ceil: 6000, cruise: 54, vmax: 75, proto: "OcuSync 4 Enterprise", payload: "EO + IR + laser + NIR", rf: "OcuSync 4E, RID.", vis: "Nacelle thermique Matrice 4.", kin: "ISR 49 min.", ac: "Quad médium.", notes: "Thermique Matrice 4." }),
  m({ id: "dji-agras-t30", name: "Agras T30", mfr: "DJI", origin: "CN", cls: "multirotor", role: "agriculture", threat: "faible", kg: 26.4, min: 16, km: 2, ceil: 200, cruise: 25, vmax: 36, proto: "DJI Agras link", rid: true, payload: "Cuve 30 L", rf: "Agras, radar 24 GHz.", vis: "Hexa agricole, rampes.", kin: "Vol rasant parcelle.", ac: "Grave, très bruyant.", notes: "Pulvérisateur agricole." }),
  m({ id: "dji-agras-t40", name: "Agras T40", mfr: "DJI", origin: "CN", role: "agriculture", threat: "faible", kg: 38, min: 18, km: 2, ceil: 200, cruise: 36, vmax: 50, proto: "DJI Agras link", rid: true, payload: "Cuve 40 L", rf: "Agras + radar.", vis: "Octo agricole massif.", kin: "Rasant linéaire.", ac: "Très grave.", notes: "Agricole lourd DJI." }),
  m({ id: "dji-flycart-30", name: "FlyCart 30", mfr: "DJI", origin: "CN", role: "logistics", threat: "moderee", kg: 42.3, min: 16, km: 16, ceil: 6000, cruise: 54, vmax: 72, proto: "OcuSync Enterprise", rid: true, payload: "Fret 30 kg, treuil", rf: "OcuSync Enterprise cargo.", vis: "Quad cargo, nacelle treuil ou caisse.", kin: "Transit fret 15 m/s.", ac: "Quad lourd.", notes: "Logistique DJI. RCS élevé." }),
  m({ id: "autel-evo-lite-plus", name: "EVO Lite+", mfr: "Autel Robotics", origin: "CN", kg: 0.835, min: 40, km: 12, ceil: 5000, cruise: 50, vmax: 68, proto: "SkyLink 2.0", payload: "Caméra 1 pouce 6K", rf: "SkyLink 2, distinct OcuSync.", vis: "Quad Autel fermé, pas de RTK mât.", kin: "40 min.", ac: "Quad médium.", notes: "Commercial Autel." }),
  m({ id: "autel-evo-ii-pro", name: "EVO II Pro V3", mfr: "Autel Robotics", origin: "CN", kg: 1.12, min: 40, km: 15, ceil: 7000, cruise: 50, vmax: 72, proto: "SkyLink 2.0", payload: "Caméra 1 pouce 6K", rf: "SkyLink 2.0.", vis: "EVO II, hélices 9 pouces.", kin: "40 min, 20 m/s.", ac: "Quad médium.", notes: "EVO II Pro civil." }),
  m({ id: "autel-evo-ii-dual", name: "EVO II Dual 640T", mfr: "Autel Robotics", origin: "CN", role: "enterprise-isr", kg: 1.17, min: 38, km: 13, ceil: 7000, cruise: 50, vmax: 72, proto: "SkyLink 2.0", payload: "EO 8K + IR 640", rf: "SkyLink, pas OcuSync.", vis: "Nacelle dual visible.", kin: "ISR hover.", ac: "Quad médium.", notes: "Thermique Autel civil." }),
  m({ id: "autel-nano-plus", name: "EVO Nano+", mfr: "Autel Robotics", origin: "CN", kg: 0.249, min: 28, km: 10, ceil: 4000, cruise: 36, vmax: 54, proto: "SkyLink", payload: "Caméra 50 MP", rf: "SkyLink compact.", vis: "Nano pliable <250 g.", kin: "Hover léger.", ac: "Quad aigu.", notes: "Concurrent Mini." }),
  m({ id: "autel-max-4n", name: "EVO Max 4N", mfr: "Autel Robotics", origin: "CN", role: "enterprise-isr", kg: 1.66, min: 42, km: 20, ceil: 7000, cruise: 54, vmax: 82, proto: "SkyLink 3.0", payload: "Starlight + IR + télémètre", rf: "SkyLink 3.0, 900 MHz option.", vis: "Max 4, nacelle night.", kin: "ISR 42 min.", ac: "Quad médium.", notes: "Night ops Autel." }),
  m({ id: "fimi-x8-se", name: "X8 SE 2022", mfr: "FIMI", origin: "CN", kg: 0.765, min: 35, km: 10, ceil: 4000, cruise: 43, vmax: 65, proto: "FIMI link", payload: "Caméra 4K", rf: "Protocole FIMI, pas DJI.", vis: "Quad Xiaomi/FIMI, bras plats.", kin: "35 min.", ac: "Quad médium.", notes: "Commercial Xiaomi/FIMI." }),
  m({ id: "fimi-x8-mini", name: "X8 Mini", mfr: "FIMI", origin: "CN", kg: 0.249, min: 31, km: 8, ceil: 4000, cruise: 36, vmax: 57, proto: "FIMI mini link", payload: "Caméra 4K", rf: "FIMI mini.", vis: "Mini FIMI.", kin: "Hover.", ac: "Quad aigu.", notes: "Mini FIMI." }),
  m({ id: "hubsan-zino-2", name: "Zino 2 Plus", mfr: "Hubsan", origin: "CN", kg: 0.69, min: 33, km: 8, ceil: 4000, cruise: 50, vmax: 68, proto: "Hubsan 2.4/5.8", payload: "Caméra 4K", rf: "Hubsan propriétaire.", vis: "Quad Hubsan, train fixe parfois.", kin: "33 min.", ac: "Quad.", notes: "Grand public Hubsan." }),
  m({ id: "yuneec-h520e", name: "H520E", mfr: "Yuneec", origin: "CN", role: "enterprise-isr", kg: 2.0, min: 30, km: 6, ceil: 5000, cruise: 40, vmax: 54, proto: "Yuneec ST16", payload: "Nacelles E90x / E30Z", rf: "ST16, 2.4 GHz.", vis: "Hexacoptère, six bras.", kin: "Hover hexa.", ac: "Hexa, 6 foyers.", notes: "Hexa commercial Yuneec (marque CN)." }),
  m({ id: "xag-v40", name: "V40", mfr: "XAG", origin: "CN", role: "agriculture", threat: "faible", kg: 20, min: 12, km: 2, ceil: 150, cruise: 36, vmax: 43, proto: "XAG SuperX", rid: false, payload: "Pulvérisation 16 L", rf: "SuperX agricole.", vis: "Quad agricole XAG.", kin: "Rasant parcelle.", ac: "Grave.", notes: "Agricole XAG." }),
  m({ id: "jouav-cw25e", name: "CW-25E", mfr: "JOUAV", origin: "CN", cls: "vtol", role: "enterprise-isr", threat: "elevee", kg: 18, min: 180, km: 50, ceil: 5000, cruise: 90, vmax: 120, proto: "JOUAV C2", rid: false, payload: "EO/IR / lidar", rf: "C2 JOUAV, hors OcuSync.", vis: "VTOL aile + rotors lift.", kin: "Transition puis 90 km/h.", ac: "Lift puis hélice.", notes: "VTOL carto chinois." }),
  m({ id: "walkera-vitus", name: "Vitus 320", mfr: "Walkera", origin: "CN", kg: 0.84, min: 25, km: 5, ceil: 4000, cruise: 40, vmax: 54, proto: "Walkera DEVO", payload: "Caméra 4K", rf: "DEVO 2.4 GHz.", vis: "Quad Walkera.", kin: "Hover.", ac: "Quad.", notes: "Commercial Walkera." }),

  // —— Drones commerciaux / tactiques légers Turquie ——
  m({ id: "baykar-mini", name: "Bayraktar Mini", mfr: "Baykar", origin: "TR", cls: "fixed-wing", role: "isr", threat: "moderee", kg: 3.5, min: 60, km: 15, ceil: 3000, cruise: 60, vmax: 90, bands: ["2.4 GHz", "UHF"], proto: "Baykar Mini C2", rid: false, payload: "EO 1 kg", rf: "C2 Baykar court rayon.", vis: "Aile fixe miniature, lancement main.", kin: "60 km/h, 1 h.", ac: "Électrique.", notes: "UAS tactique léger turc, encore en service." }),
  m({ id: "malazgirt", name: "Malazgirt", mfr: "Baykar", origin: "TR", cls: "multirotor", role: "isr", threat: "moderee", kg: 3.5, min: 45, km: 10, ceil: 1500, cruise: 40, vmax: 60, proto: "Baykar rotary C2", rid: false, payload: "EO", rf: "C2 rotary Baykar.", vis: "Quad militaire turc.", kin: "Hover ISR.", ac: "Quad.", notes: "Rotary Baykar." }),
  m({ id: "serce-2", name: "Serçe-2", mfr: "Aselsan", origin: "TR", cls: "multirotor", role: "isr", threat: "elevee", kg: 4.5, min: 30, km: 3, ceil: 500, cruise: 36, vmax: 50, proto: "Aselsan Serçe", rid: false, payload: "EO/IR, reconnaissance de zone", rf: "Liaison Aselsan courte.", vis: "Quad Aselsan, nacelle gimbal.", kin: "Hover 30 min.", ac: "Quad militaire.", notes: "ISR de proximité Aselsan." }),
  m({ id: "songar", name: "Songar", mfr: "Asisguard", origin: "TR", cls: "multirotor", role: "strike", threat: "critique", kg: 25, min: 30, km: 10, ceil: 1000, cruise: 40, vmax: 60, proto: "Asisguard C2", rid: false, payload: "Armement léger / EO", rf: "C2 militaire turc, pas RID.", vis: "Quad lourd, rail d'arme sous fuselage.", kin: "Hover armé, lent.", ac: "Quad grave.", notes: "Quad armé turc. Distinct Kargu (rodeuse)." }),
  m({ id: "boyga", name: "Boyga", mfr: "STM", origin: "TR", cls: "multirotor", role: "strike", threat: "critique", kg: 6, min: 20, km: 5, ceil: 500, cruise: 50, vmax: 80, proto: "STM Boyga", rid: false, payload: "Munition largable", rf: "STM FHSS.", vis: "Quad STM, trappe de largage.", kin: "Hover puis largage.", ac: "Quad.", notes: "Quad de largage STM." }),
  m({ id: "gozcu", name: "Gözcü", mfr: "TUSAŞ / TAI", origin: "TR", cls: "fixed-wing", role: "isr", threat: "moderee", kg: 4, min: 90, km: 20, ceil: 3000, cruise: 70, vmax: 100, proto: "TAI Gözcü C2", rid: false, payload: "EO", rf: "C2 TAI léger.", vis: "Aile fixe TAI petite.", kin: "70 km/h, 1.5 h.", ac: "Électrique.", notes: "ISR léger TAI." }),
  m({ id: "kargi", name: "Kargı", mfr: "Lentatek", origin: "TR", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 8, min: 45, km: 50, ceil: 3000, cruise: 100, vmax: 150, bands: ["UHF", "2.4 GHz"], proto: "Lentatek Kargı", rid: false, payload: "Charge anti-radar", rf: "SEAD, liaison intermittente.", vis: "Aile fixe rodeuse, entrée d'air.", kin: "Loiter puis piqué radar.", ac: "Hélice.", notes: "Rodeuse anti-radar turque." }),
  m({ id: "barkan", name: "Barkan", mfr: "STM", origin: "TR", cls: "multirotor", role: "isr", threat: "elevee", kg: 8, min: 45, km: 5, ceil: 1000, cruise: 40, vmax: 60, proto: "STM Barkan", rid: false, payload: "EO/IR + emport léger", rf: "STM C2.", vis: "Quad tactique STM plus gros que Togan.", kin: "Hover ISR.", ac: "Quad.", notes: "Quad tactique STM." }),
  m({ id: "cezeri", name: "Cezeri", mfr: "Baykar", origin: "TR", cls: "multirotor", role: "consumer", threat: "faible", kg: 120, min: 20, km: 2, ceil: 100, cruise: 40, vmax: 70, proto: "Baykar Cezeri", rid: false, payload: "eVTOL 1 passager (démo)", rf: "C2 Baykar expérimental.", vis: "eVTOL multicoptère habité, très gros.", kin: "Vol stationnaire lourd, lent.", ac: "Multi-rotors graves.", notes: "Démonstrateur eVTOL. RCS énorme, pas un UAS tactique." }),
  m({ id: "anka-3", name: "Anka-3", mfr: "TUSAŞ / TAI", origin: "TR", cls: "ucav", role: "strike", threat: "critique", kg: 6500, min: 600, km: 900, ceil: 12192, cruise: 700, vmax: 900, bands: ["SATCOM", "LOS LPI"], proto: "TAI UCAV C2", rid: false, payload: "Soute, UCAV furtif", rf: "LPI / SATCOM TAI.", vis: "Aile volante, sans empennage.", kin: "Jet subsonique.", ac: "Turboréacteur.", notes: "UCAV furtif TAI. Distinct Kızılelma (empennage)." }),

  // —— Drones commerciaux Russie ——
  m({ id: "geoscan-201", name: "Geoscan 201", mfr: "Geoscan", origin: "RU", cls: "fixed-wing", role: "enterprise-isr", kg: 8.5, min: 180, km: 40, ceil: 4000, cruise: 80, vmax: 110, bands: ["900 MHz", "2.4 GHz"], proto: "Geoscan C2", rid: false, payload: "Photo / lidar carto", rf: "C2 Geoscan digital.", vis: "Aile fixe carto, fuselage pod.", kin: "80 km/h, 3 h.", ac: "Électrique.", notes: "Carto civile russe." }),
  m({ id: "geoscan-401", name: "Geoscan 401", mfr: "Geoscan", origin: "RU", role: "enterprise-isr", kg: 2.8, min: 40, km: 8, ceil: 2000, cruise: 36, vmax: 50, proto: "Geoscan copter", rid: false, payload: "Photo / lidar", rf: "C2 Geoscan 2.4.", vis: "Quad carto russe.", kin: "Hover mapping.", ac: "Quad.", notes: "Multirotor Geoscan." }),
  m({ id: "geoscan-gemini", name: "Gemini", mfr: "Geoscan", origin: "RU", cls: "vtol", role: "enterprise-isr", kg: 12, min: 70, km: 25, ceil: 3000, cruise: 70, vmax: 90, proto: "Geoscan VTOL", rid: false, payload: "Carto EO", rf: "Geoscan VTOL.", vis: "VTOL aile + rotors.", kin: "Transition 70 km/h.", ac: "Lift puis hélice.", notes: "VTOL carto russe." }),
  m({ id: "supercam-s150", name: "SuperCam S150", mfr: "Unmanned Systems", origin: "RU", cls: "fixed-wing", role: "enterprise-isr", kg: 7, min: 150, km: 40, ceil: 4000, cruise: 80, vmax: 110, bands: ["900 MHz"], proto: "SuperCam digital", rid: false, payload: "EO carto", rf: "900 MHz SuperCam.", vis: "Aile haute petite, V-tail.", kin: "80 km/h.", ac: "Électrique.", notes: "Carto SuperCam civil/para." }),
  m({ id: "zala-421-08", name: "ZALA 421-08M", mfr: "ZALA Aero", origin: "RU", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 2.5, min: 90, km: 15, ceil: 3600, cruise: 65, vmax: 120, bands: ["900 MHz"], proto: "ZALA ISR", rid: false, payload: "EO 0.3 kg", rf: "ZALA 900 MHz.", vis: "Mini aile ZALA, lancement main.", kin: "65 km/h, 90 min.", ac: "Électrique discret.", notes: "Mini ISR ZALA." }),
  m({ id: "eleron-7", name: "Eleron-7", mfr: "ENICS", origin: "RU", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 8, min: 180, km: 60, ceil: 4000, cruise: 85, vmax: 140, bands: ["430 MHz", "900 MHz"], proto: "ENICS C2", rid: false, payload: "EO/IR", rf: "UHF ENICS.", vis: "Aile plus grande qu'Eleron-3.", kin: "85 km/h, 3 h.", ac: "Piston/électrique.", notes: "ISR ENICS moyen." }),
  m({ id: "granat-1", name: "Granat-1", mfr: "Izhmash", origin: "RU", cls: "fixed-wing", role: "isr", threat: "moderee", kg: 2.4, min: 75, km: 15, ceil: 3000, cruise: 60, vmax: 90, bands: ["430 MHz"], proto: "Granat C2", rid: false, payload: "EO", rf: "UHF Granat.", vis: "Mini aile, lancement main.", kin: "60 km/h.", ac: "Électrique.", notes: "ISR d'unité léger." }),
  m({ id: "granat-2", name: "Granat-2", mfr: "Izhmash", origin: "RU", cls: "fixed-wing", role: "isr", threat: "moderee", kg: 3.8, min: 120, km: 25, ceil: 3500, cruise: 70, vmax: 110, bands: ["430 MHz"], proto: "Granat C2", rid: false, payload: "EO", rf: "UHF Granat.", vis: "Aile Granat intermédiaire.", kin: "70 km/h.", ac: "Électrique.", notes: "Entre Granat-1 et Granat-4." }),
  m({ id: "tachyon", name: "Tachyon", mfr: "Izhmash", origin: "RU", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 5, min: 120, km: 40, ceil: 4000, cruise: 80, vmax: 120, bands: ["430 MHz", "900 MHz"], proto: "Tachyon C2", rid: false, payload: "EO/IR", rf: "UHF russe.", vis: "Aile fixe tactique.", kin: "80 km/h.", ac: "Électrique.", notes: "ISR Tachyon." }),
  m({ id: "kartograf", name: "Kartograf", mfr: "ZALA Aero", origin: "RU", cls: "fixed-wing", role: "enterprise-isr", kg: 4.5, min: 120, km: 30, ceil: 3000, cruise: 75, vmax: 110, proto: "ZALA Kartograf", rid: false, payload: "Photo carto", rf: "ZALA carto.", vis: "Aile carto ZALA.", kin: "75 km/h.", ac: "Électrique.", notes: "Carto ZALA." }),
  m({ id: "ptero-g0", name: "Ptero", mfr: "AFM-Servers / Ptero", origin: "RU", cls: "fixed-wing", role: "enterprise-isr", kg: 6, min: 150, km: 40, ceil: 3500, cruise: 80, vmax: 110, proto: "Ptero C2", rid: false, payload: "Photo", rf: "C2 Ptero.", vis: "Aile carto russe.", kin: "80 km/h.", ac: "Électrique.", notes: "Carto Ptero." }),
  m({ id: "lancet-1", name: "Lancet-1", mfr: "ZALA Aero", origin: "RU", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 5, min: 30, km: 40, ceil: 4000, cruise: 80, vmax: 110, bands: ["900 MHz", "2.4 GHz"], proto: "ZALA FHSS", rid: false, payload: "Charge ~1 kg", rf: "ZALA, plus léger que Lancet-3.", vis: "X-wing miniature.", kin: "Loiter puis piqué.", ac: "Hélice électrique.", notes: "Rodeuse légère ZALA." }),
  m({ id: "geran-1", name: "Geran-1", mfr: "Alabuga / Geran", origin: "RU", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 90, min: 360, km: 1000, ceil: 2500, cruise: 140, vmax: 160, bands: ["GNSS"], proto: "INS/GNSS", rid: false, payload: "Charge ~10–20 kg, delta", rf: "Peu de C2 — GNSS/INS.", vis: "Delta plus petite que Geran-2.", kin: "140 km/h constant.", ac: "Deux-temps bruyant.", notes: "Rodeuse longue portée légère." }),
  m({ id: "altius", name: "Altius-RU", mfr: "Ural Civil Aviation", origin: "RU", cls: "male", role: "isr", threat: "critique", kg: 5000, min: 1440, km: 6000, ceil: 12000, cruise: 250, vmax: 350, bands: ["SATCOM", "LOS"], proto: "Altius C2", rid: false, payload: "ISR 1 t", rf: "SATCOM MALE russe.", vis: "MALE bimoteur ~28 m.", kin: "MALE 24 h, 250 km/h.", ac: "Deux turbos, haute altitude.", notes: "MALE lourd russe." }),
  m({ id: "merlin-vr", name: "Merlin-VR", mfr: "JSC NPO Strela", origin: "RU", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 4.5, min: 120, km: 40, ceil: 4000, cruise: 70, vmax: 120, bands: ["900 MHz"], proto: "Merlin C2", rid: false, payload: "EO", rf: "C2 Merlin.", vis: "Aile fixe compacte.", kin: "70 km/h.", ac: "Électrique.", notes: "ISR Merlin-VR." }),

  // —— UAS mil. Chine additionnels ——
  m({ id: "wing-loong-1", name: "Wing Loong I", mfr: "AVIC / CAC", origin: "CN", cls: "male", role: "strike", threat: "critique", kg: 1100, min: 1200, km: 4000, ceil: 7500, cruise: 200, vmax: 280, bands: ["L-band LOS", "SATCOM"], proto: "CAC C2", rid: false, payload: "200 kg", rf: "LOS L-band + SATCOM.", vis: "MALE ~14 m, V-tail, plus petit que WL-II.", kin: "200 km/h, 20 h.", ac: "Piston haute altitude.", notes: "MALE export 1re gén." }),
  m({ id: "wing-loong-3", name: "Wing Loong-3", mfr: "AVIC / CAC", origin: "CN", cls: "male", role: "strike", threat: "critique", kg: 4200, min: 1920, km: 5000, ceil: 10000, cruise: 300, vmax: 400, bands: ["SATCOM Ku", "LOS"], proto: "CAC C2 lourd", rid: false, payload: "2 000 kg", rf: "SATCOM lourd.", vis: "MALE large, plus massif que WL-II.", kin: "300 km/h, 32 h.", ac: "Turbo-hélice.", notes: "MALE lourd CAC." }),
  m({ id: "ch-3", name: "CH-3 Rainbow", mfr: "CASC / CAAA", origin: "CN", cls: "male", role: "strike", threat: "critique", kg: 640, min: 720, km: 200, ceil: 5000, cruise: 180, vmax: 220, bands: ["LOS"], proto: "CASC C2", rid: false, payload: "100 kg", rf: "LOS CASC.", vis: "MALE ~8 m, empennage V.", kin: "180 km/h.", ac: "Piston.", notes: "Ancien Rainbow, encore exporté." }),
  m({ id: "bzk-005", name: "BZK-005", mfr: "Harbin / AVIC", origin: "CN", cls: "male", role: "isr", threat: "elevee", kg: 1250, min: 2400, ceil: 8000, km: 2400, cruise: 170, vmax: 210, bands: ["LOS", "SATCOM"], proto: "AVIC ISR C2", rid: false, payload: "ISR 150 kg", rf: "LOS/SATCOM ISR.", vis: "MALE ~11 m, double dérive.", kin: "170 km/h, 40 h.", ac: "Piston.", notes: "ISR MALE Harbin." }),
  m({ id: "cloud-shadow", name: "Cloud Shadow", mfr: "AVIC / CAC", origin: "CN", cls: "ucav", role: "strike", threat: "critique", kg: 3000, min: 360, km: 2000, ceil: 14000, cruise: 550, vmax: 700, bands: ["SATCOM", "LOS"], proto: "CAC jet C2", rid: false, payload: "400 kg", rf: "C2 jet CAC.", vis: "UCAV jet, entrée d'air dorsale.", kin: "Subsonique haut.", ac: "Turboréacteur.", notes: "UCAV jet CAC." }),
  m({ id: "wz-7", name: "WZ-7 Soaring Dragon", mfr: "AVIC / Chengdu", origin: "CN", cls: "male", role: "isr", threat: "critique", kg: 7500, min: 600, km: 2000, ceil: 18000, cruise: 700, vmax: 750, bands: ["SATCOM"], proto: "Chengdu HALE C2", rid: false, payload: "ISR / radar", rf: "SATCOM HALE.", vis: "Aile tandem jointe, silhouette unique.", kin: "HALE 18 km, 700 km/h.", ac: "Jet, inaudible au sol.", notes: "HALE ISR. Silhouette tandem discriminante." }),
  m({ id: "ch-901", name: "CH-901", mfr: "CASC", origin: "CN", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 9, min: 40, km: 15, ceil: 2000, cruise: 90, vmax: 150, bands: ["2.4 GHz", "UHF"], proto: "CASC rodeuse", rid: false, payload: "Charge 3.5 kg", rf: "FHSS courte.", vis: "Aile fixe miniature tube.", kin: "Loiter puis piqué.", ac: "Hélice.", notes: "Rodeuse Rainbow légère." }),

  // —— Chasse Chine ——
  m({ id: "j-10c", name: "J-10C", mfr: "CAC / Chengdu", origin: "CN", cls: "chasse", role: "fighter", kg: 13200, min: 120, km: 1800, ceil: 18000, cruise: 1100, vmax: 2335, proto: "IFF + liaison de données PLAAF", rid: false, payload: "Canon + 11 points d'emport", rf: "Radar AESA, IFF Mode S, datalink. Pas d'ISM.", vis: "Mono-réacteur canard, entrée ventrale.", kin: "Mach 1.2+ transit, 8–12 km, virages serrés chasse.", ac: "Turboréacteur, bang possible.", notes: "Chasseur CAC. Identification radar 3D + silhouette canard." }),
  m({ id: "j-11b", name: "J-11B", mfr: "Shenyang / SAC", origin: "CN", cls: "chasse", role: "fighter", kg: 17500, min: 150, km: 3500, ceil: 18500, cruise: 980, vmax: 2500, proto: "IFF + datalink PLAAF", rid: false, payload: "Flanker armé, 10 points", rf: "Radar aéroporté, IFF.", vis: "Biréacteur Flanker, nez Su-27, dérives jumelles.", kin: "Mach 1.8, rayon large.", ac: "Deux réacteurs.", notes: "Flanker chinois. Distinguer du Su-30SM par IFF / datalink PLAAF." }),
  m({ id: "j-16", name: "J-16", mfr: "Shenyang / SAC", origin: "CN", cls: "chasse", role: "fighter", kg: 17800, min: 180, km: 3000, ceil: 17300, cruise: 980, vmax: 2450, proto: "IFF + datalink PLAAF", rid: false, payload: "Multirôle lourd, 12 points", rf: "AESA, IFF.", vis: "Flanker biplace, nez plus long que J-11.", kin: "Multirôle, 10 km typique.", ac: "Biréacteur.", notes: "Dérivé Flanker biplace." }),
  m({ id: "j-15", name: "J-15", mfr: "Shenyang / SAC", origin: "CN", cls: "chasse", role: "fighter", kg: 17500, min: 120, km: 2800, ceil: 20000, cruise: 980, vmax: 2500, proto: "IFF naval PLA", rid: false, payload: "Embarqué, crosse d'appontage", rf: "Radar + IFF naval.", vis: "Flanker embarqué, canards, crosse.", kin: "Profil porte-avions, 8–10 km.", ac: "Biréacteur.", notes: "Chasse embarquée. Rare hors mer de Chine — toute piste J-15 hors théâtre naval est à corréler." }),
  m({ id: "j-20", name: "J-20", mfr: "CAC / Chengdu", origin: "CN", cls: "chasse", role: "fighter", kg: 19600, min: 180, km: 5500, ceil: 20000, cruise: 1400, vmax: 2450, proto: "Liaison LPI + IFF furtif", rid: false, payload: "Soutes internes", rf: "LPI, radar discret, IFF bas PAPR.", vis: "Canards + aile delta, 5e gén, deux réacteurs.", kin: "Supercroisière possible, haute altitude.", ac: "Biréacteur, plus discret en LPI.", notes: "Chasse furtive. RF classique insuffisante — radar 3D + EO." }),
  m({ id: "j-35", name: "J-35 / FC-31", mfr: "Shenyang / SAC", origin: "CN", cls: "chasse", role: "fighter", kg: 17500, min: 150, km: 2000, ceil: 16000, cruise: 1200, vmax: 2200, proto: "IFF + LPI SAC", rid: false, payload: "Soutes, 5e gén moyen", rf: "LPI, IFF.", vis: "Biréacteur furtif plus petit que J-20, empennage double.", kin: "Mach 1.8, 10 km.", ac: "Biréacteur.", notes: "5e gén Shenyang. Ne pas confondre avec J-20 (canards)." }),
  m({ id: "jh-7a", name: "JH-7A", mfr: "Xian / CAC", origin: "CN", cls: "chasse", role: "fighter", kg: 14500, min: 180, km: 3700, ceil: 16000, cruise: 900, vmax: 1800, proto: "IFF PLAAF", rid: false, payload: "Chasse-bombardier, 9 points", rf: "Radar attaque au sol + IFF.", vis: "Biréacteur aile haute, nez allongé.", kin: "Subsonique haut / Mach 1.6.", ac: "Biréacteur.", notes: "Chasse-bombardier Xian." }),
  m({ id: "jf-17", name: "JF-17 / FC-1", mfr: "CAC / PAC", origin: "CN", cls: "chasse", role: "fighter", kg: 9800, min: 120, km: 2000, ceil: 16920, cruise: 1000, vmax: 2200, proto: "IFF + datalink CAC", rid: false, payload: "Multirôle léger", rf: "Radar KLJ, IFF.", vis: "Mono-réacteur, prises latérales, taille MiG-21 modernisé.", kin: "Mach 1.6, léger.", ac: "Mono-réacteur.", notes: "Chasse léger CAC (export). Mandat origine Chine." }),
  m({ id: "j-8f", name: "J-8F", mfr: "Shenyang / SAC", origin: "CN", cls: "chasse", role: "fighter", kg: 9820, min: 90, km: 1500, ceil: 20000, cruise: 900, vmax: 2300, proto: "IFF PLAAF legacy", rid: false, payload: "Chasse interception", rf: "Radar ancien, IFF.", vis: "Biréacteur nez pointu, aile delta, héritage J-8.", kin: "Intercepteur haute altitude.", ac: "Biréacteur.", notes: "Legacy. Encore possible en export / réserve." }),

  // —— Chasse Russie ——
  m({ id: "su-27", name: "Su-27", mfr: "Sukhoi", origin: "RU", cls: "chasse", role: "fighter", kg: 16380, min: 150, km: 3500, ceil: 18500, cruise: 980, vmax: 2500, proto: "IFF russe + datalink", rid: false, payload: "Chasse supérieure", rf: "Radar N001, IFF Parol.", vis: "Flanker original, dérives jumelles, becs.", kin: "Mach 2, rayon large.", ac: "AL-31F ×2.", notes: "Flanker de base. Corréler IFF russe vs J-11 chinois." }),
  m({ id: "su-30sm", name: "Su-30SM", mfr: "Sukhoi / Irkut", origin: "RU", cls: "chasse", role: "fighter", kg: 17500, min: 180, km: 3000, ceil: 17300, cruise: 950, vmax: 2120, proto: "IFF + datalink VKS", rid: false, payload: "Multirôle biplace", rf: "Bars, IFF.", vis: "Flanker biplace, canards, perche de ravitaillement.", kin: "Multirôle, 8–11 km.", ac: "Biréacteur.", notes: "Cheval de bataille VKS / export." }),
  m({ id: "su-35s", name: "Su-35S", mfr: "Sukhoi", origin: "RU", cls: "chasse", role: "fighter", kg: 19000, min: 150, km: 3600, ceil: 18000, cruise: 1100, vmax: 2500, proto: "IFF + datalink VKS", rid: false, payload: "Chasse 4++ , 12 points", rf: "Irbis-E PESA, IFF.", vis: "Flanker 4++, pas de canard, tuyères 3D.", kin: "Super-manœuvrant, Mach 2.25.", ac: "AL-41F1S ×2.", notes: "Flanker 4++. Tuyères TVC discriminantes en EO." }),
  m({ id: "su-57", name: "Su-57", mfr: "Sukhoi", origin: "RU", cls: "chasse", role: "fighter", kg: 18500, min: 180, km: 3500, ceil: 20000, cruise: 1500, vmax: 2600, proto: "Liaison LPI + IFF 5e gén", rid: false, payload: "Soutes internes", rf: "LPI, AESA, IFF bas PAPR.", vis: "5e gén, ailes rhomboïdes, deux réacteurs, LEVCON.", kin: "Supercroisière, haute altitude.", ac: "Biréacteur.", notes: "Chasse furtive russe. Fusion radar/EO obligatoire." }),
  m({ id: "mig-29smt", name: "MiG-29SMT", mfr: "MiG / RAC", origin: "RU", cls: "chasse", role: "fighter", kg: 11000, min: 100, km: 1800, ceil: 18000, cruise: 1050, vmax: 2400, proto: "IFF + datalink VKS", rid: false, payload: "Chasse légère, 7 points", rf: "N019 / Zhuk, IFF.", vis: "Biréacteur compact, prises latérales, plus petit que Flanker.", kin: "Mach 2, rayon plus court.", ac: "RD-33 ×2.", notes: "Fulcrum modernisé. Silhouette plus petite que Su-30." }),
  m({ id: "mig-31bm", name: "MiG-31BM", mfr: "MiG / Sokol", origin: "RU", cls: "chasse", role: "fighter", kg: 21820, min: 150, km: 3000, ceil: 20600, cruise: 1500, vmax: 3000, proto: "IFF intercepteur + datalink", rid: false, payload: "Interception longue, R-37", rf: "Zaslon-AM, IFF.", vis: "Biréacteur massif, ailes trapèze, biplace tandem.", kin: "Mach 2.8, 15–20 km, transit très rapide.", ac: "D-30F6 ×2, signature jet lourde.", notes: "Intercepteur. Vitesse et altitude hors enveloppe UAS." }),
  m({ id: "mig-35", name: "MiG-35", mfr: "MiG / RAC", origin: "RU", cls: "chasse", role: "fighter", kg: 11000, min: 120, km: 2000, ceil: 17500, cruise: 1050, vmax: 2400, proto: "IFF + AESA MiG", rid: false, payload: "Multirôle 4++", rf: "Zhuk-A AESA, IFF.", vis: "Fulcrum 4++, LERX, opto-sphère.", kin: "Mach 2, 10 km.", ac: "RD-33MK ×2.", notes: "Évolution MiG-29." }),
  m({ id: "su-34", name: "Su-34", mfr: "Sukhoi", origin: "RU", cls: "chasse", role: "fighter", kg: 22500, min: 240, km: 4000, ceil: 17000, cruise: 900, vmax: 1900, proto: "IFF + datalink VKS", rid: false, payload: "Chasse-bombardier, 12 t", rf: "Lenets, IFF.", vis: "Nez plat biplace côte-à-côte, Flanker élargi.", kin: "Subsonique / Mach 1.8, profil frappe.", ac: "AL-31F ×2.", notes: "Fullback. Nez plat discriminant en EO." }),
  m({ id: "su-24m", name: "Su-24M", mfr: "Sukhoi", origin: "RU", cls: "chasse", role: "fighter", kg: 22300, min: 150, km: 2500, ceil: 17000, cruise: 850, vmax: 1650, proto: "IFF VKS legacy", rid: false, payload: "Frappe, géométrie variable", rf: "Puma, IFF.", vis: "Aile à géométrie variable, nez long.", kin: "Basse altitude rapide possible.", ac: "AL-21F ×2.", notes: "Fencer. Aile sweep = marqueur visuel fort." }),
  m({ id: "su-25sm", name: "Su-25SM", mfr: "Sukhoi", origin: "RU", cls: "chasse", role: "fighter", kg: 10760, min: 120, km: 750, ceil: 7000, cruise: 700, vmax: 950, proto: "IFF VKS", rid: false, payload: "Appui-feu, 4.4 t", rf: "Radar/EO d'appui, IFF.", vis: "Biréacteur trapu, aile droite, train blindé.", kin: "Subsonique rasant 50–1000 m.", ac: "R-95 ×2, bruyant bas.", notes: "Frogfoot. Profil rasant distinct des chasseurs haute alt." }),

  // —— Chasse Turquie ——
  m({ id: "tf-kaan", name: "TF Kaan", mfr: "TUSAŞ / TAI", origin: "TR", cls: "chasse", role: "fighter", kg: 22600, min: 150, km: 2000, ceil: 17000, cruise: 1400, vmax: 2200, proto: "IFF + datalink TAI MMU", rid: false, payload: "Soutes, 5e gén turc", rf: "AESA milli / LPI, IFF TAF.", vis: "Biréacteur furtif, empennage double, sans canard.", kin: "Mach 1.8, haute altitude.", ac: "F110 ×2 (early) / moteur national.", notes: "Chasse 5e gén TAI. En montée opérationnelle." }),
  m({ id: "hurjet", name: "Hürjet", mfr: "TUSAŞ / TAI", origin: "TR", cls: "chasse", role: "trainer", threat: "elevee", kg: 6500, min: 90, km: 2600, ceil: 13700, cruise: 900, vmax: 1400, proto: "IFF TAF + radio UHF", rid: false, payload: "Entraînement / léger air-sol", rf: "IFF, radio UHF/VHF, radar léger option.", vis: "Mono-réacteur, aile haute, tandem.", kin: "Mach 1.4, 7–12 km.", ac: "F404, jet léger.", notes: "Jet d'entraînement armable. Plus lent qu'un Kaan / F-16." }),

  // —— UAS Iran ——
  m({ id: "shahed-136", name: "Shahed-136", mfr: "Shahed Aviation", origin: "IR", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 200, min: 720, km: 2000, ceil: 4000, cruise: 185, vmax: 200, bands: ["GNSS"], proto: "INS/GNSS", rid: false, payload: "Charge ~50 kg, delta", rf: "Peu de C2 — GNSS/INS. Distinct Geran-2 (prod. RU).", vis: "Aile delta, moteur poussé, bout d'aile relevé.", kin: "185 km/h constant, longue portée.", ac: "Deux-temps bruyant.", notes: "Rodeuse iranienne d'origine. Geran-2 = copie/prod. russe." }),
  m({ id: "shahed-129", name: "Shahed-129", mfr: "Shahed Aviation", origin: "IR", cls: "male", role: "strike", threat: "critique", kg: 900, min: 1440, km: 1700, ceil: 7300, cruise: 150, vmax: 210, bands: ["LOS", "SATCOM"], proto: "Shahed C2", rid: false, payload: "ISR / 4 missiles Sadid", rf: "LOS/SATCOM iranien.", vis: "MALE ~8 m, empennage V, nez bulbe.", kin: "150 km/h, 24 h.", ac: "Piston.", notes: "MALE Shahed. Mandat IR." }),
  m({ id: "shahed-149", name: "Shahed-149 Gaza", mfr: "Shahed Aviation", origin: "IR", cls: "male", role: "strike", threat: "critique", kg: 3500, min: 2100, km: 4000, ceil: 10500, cruise: 250, vmax: 400, bands: ["SATCOM"], proto: "Shahed SATCOM", rid: false, payload: "ISR / frappe 13 m", rf: "SATCOM MALE iranien.", vis: "MALE large, plus grand que 129.", kin: "250 km/h, 35 h.", ac: "Turbo-hélice.", notes: "MALE lourd Shahed-149." }),
  m({ id: "mohajer-6", name: "Mohajer-6", mfr: "Qods Aviation", origin: "IR", cls: "male", role: "strike", threat: "critique", kg: 600, min: 720, km: 200, ceil: 5400, cruise: 140, vmax: 200, bands: ["LOS"], proto: "Qods C2", rid: false, payload: "ISR + 4 missiles", rf: "LOS Qods.", vis: "MALE ~6 m, double dérive.", kin: "140 km/h, 12 h.", ac: "Piston.", notes: "MALE tactique Qods." }),
  m({ id: "mohajer-4", name: "Mohajer-4", mfr: "Qods Aviation", origin: "IR", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 175, min: 360, km: 150, ceil: 4500, cruise: 120, vmax: 180, bands: ["LOS"], proto: "Qods C2", rid: false, payload: "EO/IR", rf: "LOS Qods.", vis: "Aile haute, empennage classique.", kin: "120 km/h, 6 h.", ac: "Piston.", notes: "ISR Qods antérieur au M-6." }),
  m({ id: "ababil-3", name: "Ababil-3", mfr: "HESA", origin: "IR", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 95, min: 240, km: 100, ceil: 5000, cruise: 200, vmax: 300, bands: ["LOS"], proto: "HESA C2", rid: false, payload: "EO", rf: "LOS HESA.", vis: "Aile delta, nez pointu.", kin: "200 km/h.", ac: "Piston.", notes: "ISR HESA Ababil-3." }),
  m({ id: "ababil-5", name: "Ababil-5", mfr: "HESA", origin: "IR", cls: "male", role: "strike", threat: "critique", kg: 450, min: 480, km: 480, ceil: 5400, cruise: 180, vmax: 250, bands: ["LOS"], proto: "HESA C2", rid: false, payload: "ISR / frappe", rf: "LOS HESA.", vis: "MALE HESA, plus massif qu'Ababil-3.", kin: "180 km/h, 8 h.", ac: "Piston.", notes: "MALE Ababil-5." }),
  m({ id: "karrar", name: "Karrar", mfr: "HESA", origin: "IR", cls: "ucav", role: "strike", threat: "critique", kg: 700, min: 60, km: 1000, ceil: 9000, cruise: 700, vmax: 900, bands: ["LOS"], proto: "HESA jet C2", rid: false, payload: "UCAV jet, bombe / missile", rf: "C2 jet HESA.", vis: "Jet mono-réacteur, entrée dorsale.", kin: "Subsonique haut, 900 km/h.", ac: "Turboréacteur.", notes: "UCAV jet iranien." }),
  m({ id: "arash-2", name: "Arash-2", mfr: "HESA", origin: "IR", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 200, min: 240, km: 1200, ceil: 3500, cruise: 200, vmax: 250, bands: ["GNSS"], proto: "INS/GNSS", rid: false, payload: "Charge rodeuse", rf: "GNSS/INS, peu de C2.", vis: "Delta plus ramassé que Shahed-136.", kin: "200 km/h.", ac: "Deux-temps.", notes: "Rodeuse HESA Arash-2." }),
  m({ id: "meraj-532", name: "Meraj-532", mfr: "IRGC / HESA", origin: "IR", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 450, min: 600, km: 1500, ceil: 4000, cruise: 180, vmax: 220, bands: ["GNSS"], proto: "INS/GNSS", rid: false, payload: "Charge lourde", rf: "GNSS/INS.", vis: "Delta lourd.", kin: "180 km/h, longue portée.", ac: "Piston.", notes: "Rodeuse lourde Meraj." }),
  m({ id: "yasir", name: "Yasir", mfr: "HESA", origin: "IR", cls: "fixed-wing", role: "isr", threat: "elevee", kg: 25, min: 90, km: 15, ceil: 3000, cruise: 80, vmax: 120, bands: ["LOS"], proto: "HESA léger", rid: false, payload: "EO", rf: "LOS court.", vis: "Mini aile, lancement catapulte.", kin: "80 km/h, 1.5 h.", ac: "Électrique/piston.", notes: "ISR léger (copie ScanEagle)." }),
  m({ id: "shahed-238", name: "Shahed-238", mfr: "Shahed Aviation", origin: "IR", cls: "loitering", role: "loitering-munition", threat: "critique", kg: 230, min: 360, km: 1000, ceil: 4000, cruise: 350, vmax: 500, bands: ["GNSS"], proto: "INS/GNSS jet", rid: false, payload: "Rodeuse à turboréacteur", rf: "GNSS/INS, signature jet.", vis: "Delta à réacteur, plus rapide que 136.", kin: "350 km/h.", ac: "Turboréacteur, pas deux-temps.", notes: "Évolution jet du Shahed-136." }),
  m({ id: "fotros", name: "Fotros", mfr: "IRGC", origin: "IR", cls: "male", role: "isr", threat: "critique", kg: 3500, min: 1800, km: 2000, ceil: 7500, cruise: 220, vmax: 300, bands: ["SATCOM"], proto: "IRGC MALE C2", rid: false, payload: "ISR / frappe", rf: "SATCOM.", vis: "MALE ~16 m, double dérive.", kin: "220 km/h, 30 h.", ac: "Piston.", notes: "MALE IRGC Fotros." }),
];
