import type { ProtectedSite, SensorSite } from "./types";
import { AO } from "./geo";

export const SENSOR_SITES: SensorSite[] = [
  {
    id: "rad-1",
    name: "RADAR-1 FTTJ",
    kind: "radar",
    lat: AO.airport.lat + 0.012,
    lon: AO.airport.lon - 0.008,
    rangeKm: 220,
    online: true,
  },
  {
    id: "rad-n",
    name: "IFF-N Farcha",
    kind: "radar",
    lat: 12.158,
    lon: 15.018,
    rangeKm: 90,
    online: true,
  },
  {
    id: "rad-s",
    name: "IFF-S Chagoua",
    kind: "radar",
    lat: 12.105,
    lon: 15.095,
    rangeKm: 85,
    online: true,
  },
  {
    id: "rad-2",
    name: "RADAR-2 Moundou",
    kind: "radar",
    lat: 8.566,
    lon: 16.077,
    rangeKm: 180,
    online: true,
  },
  {
    id: "rad-3",
    name: "RADAR-3 Abéché",
    kind: "radar",
    lat: 13.829,
    lon: 20.832,
    rangeKm: 200,
    online: true,
  },
  {
    id: "rad-4",
    name: "RADAR-4 Bol",
    kind: "radar",
    lat: 13.458,
    lon: 14.715,
    rangeKm: 160,
    online: true,
  },
  {
    id: "rad-5",
    name: "RADAR-5 Faya",
    kind: "radar",
    lat: 17.926,
    lon: 19.104,
    rangeKm: 200,
    online: true,
  },
  {
    id: "rad-6",
    name: "RADAR-6 Geneina",
    kind: "radar",
    lat: 13.45,
    lon: 22.447,
    rangeKm: 180,
    online: true,
  },
  {
    id: "rad-7",
    name: "RADAR-7 El Fasher",
    kind: "radar",
    lat: 13.628,
    lon: 25.35,
    rangeKm: 200,
    online: true,
  },
  {
    id: "rad-8",
    name: "RADAR-8 Agadez",
    kind: "radar",
    lat: 16.974,
    lon: 7.991,
    rangeKm: 190,
    online: true,
  },
  {
    id: "rad-9",
    name: "RADAR-9 Khartoum",
    kind: "radar",
    lat: 15.501,
    lon: 32.532,
    rangeKm: 220,
    online: true,
  },
  {
    id: "rf-a",
    name: "RF-A Farcha",
    kind: "rf",
    lat: 12.158,
    lon: 15.018,
    rangeKm: 90,
    online: true,
  },
  {
    id: "rf-b",
    name: "RF-B Chagoua",
    kind: "rf",
    lat: 12.105,
    lon: 15.095,
    rangeKm: 80,
    online: true,
  },
  {
    id: "rf-c",
    name: "RF-C OTH Sahel",
    kind: "rf",
    lat: 12.4,
    lon: 15.2,
    rangeKm: 4200,
    online: true,
  },
  {
    id: "rf-d",
    name: "RF-D Mongo",
    kind: "rf",
    lat: 12.184,
    lon: 18.693,
    rangeKm: 140,
    online: true,
  },
  {
    id: "rf-e",
    name: "RF-E Geneina",
    kind: "rf",
    lat: 13.45,
    lon: 22.447,
    rangeKm: 380,
    online: true,
  },
  {
    id: "rf-f",
    name: "RF-F Khartoum",
    kind: "rf",
    lat: 15.5,
    lon: 32.53,
    rangeKm: 450,
    online: true,
  },
  {
    id: "rf-g",
    name: "RF-G Agadez",
    kind: "rf",
    lat: 16.97,
    lon: 7.99,
    rangeKm: 400,
    online: true,
  },
  {
    id: "rad-10",
    name: "RADAR-10 Niamey",
    kind: "radar",
    lat: 13.48,
    lon: 2.17,
    rangeKm: 200,
    online: true,
  },
  {
    id: "rad-11",
    name: "RADAR-11 Gao",
    kind: "radar",
    lat: 16.27,
    lon: -0.05,
    rangeKm: 180,
    online: true,
  },
  {
    id: "rad-12",
    name: "RADAR-12 Ouagadougou",
    kind: "radar",
    lat: 12.35,
    lon: -1.51,
    rangeKm: 180,
    online: true,
  },
  {
    id: "rad-13",
    name: "RADAR-13 Bamako",
    kind: "radar",
    lat: 12.53,
    lon: -7.95,
    rangeKm: 200,
    online: true,
  },
  {
    id: "rad-14",
    name: "RADAR-14 Nouakchott",
    kind: "radar",
    lat: 18.1,
    lon: -15.95,
    rangeKm: 180,
    online: true,
  },
  {
    id: "rf-h",
    name: "RF-H Bamako",
    kind: "rf",
    lat: 12.64,
    lon: -8.0,
    rangeKm: 380,
    online: true,
  },
  {
    id: "rf-i",
    name: "RF-I Ouagadougou",
    kind: "rf",
    lat: 12.37,
    lon: -1.53,
    rangeKm: 320,
    online: true,
  },
  {
    id: "rf-j",
    name: "RF-J Niamey",
    kind: "rf",
    lat: 13.51,
    lon: 2.11,
    rangeKm: 360,
    online: true,
  },
  {
    id: "eo-1",
    name: "EO/IR Centre",
    kind: "eoir",
    lat: AO.city.lat + 0.006,
    lon: AO.city.lon + 0.004,
    rangeKm: 22,
    online: true,
  },
  {
    id: "aco-n",
    name: "ACO-N",
    kind: "acoustic",
    lat: 12.19,
    lon: 15.06,
    rangeKm: 8,
    online: true,
  },
  {
    id: "aco-s",
    name: "ACO-S",
    kind: "acoustic",
    lat: 12.09,
    lon: 15.05,
    rangeKm: 8,
    online: true,
  },
  {
    id: "aco-c",
    name: "ACO-C",
    kind: "acoustic",
    lat: 12.134,
    lon: 15.056,
    rangeKm: 6,
    online: true,
  },
  {
    id: "aco-e",
    name: "ACO-E",
    kind: "acoustic",
    lat: 12.12,
    lon: 15.11,
    rangeKm: 7,
    online: true,
  },
];

export const PROTECTED_SITES: ProtectedSite[] = [
  {
    id: "fttj",
    name: "FTTJ",
    kind: "aerodrome",
    lat: AO.airport.lat,
    lon: AO.airport.lon,
    radiusKm: 3.2,
  },
  {
    id: "palais",
    name: "Palais",
    kind: "palais",
    lat: 12.113,
    lon: 15.074,
    radiusKm: 1.6,
  },
  {
    id: "kassei",
    name: "Camp Kassai",
    kind: "camp",
    lat: 12.118,
    lon: 15.038,
    radiusKm: 1.4,
  },
  {
    id: "nation",
    name: "Place de la Nation",
    kind: "ministere",
    lat: 12.134,
    lon: 15.049,
    radiusKm: 0.9,
  },
  {
    id: "chagoua",
    name: "Pont Chagoua",
    kind: "pont",
    lat: 12.102,
    lon: 15.088,
    radiusKm: 0.8,
  },
];

export const ACOUSTIC_SITES = SENSOR_SITES.filter((s) => s.kind === "acoustic");
