/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as CapteursRouteImport } from './routes/capteurs'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as DivisionRouteImport } from './routes/division'
import { Route as IdentRouteImport } from './routes/ident'
import { Route as IffRouteImport } from './routes/iff'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuartRouteImport } from './routes/quart'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as SentinelleRouteImport } from './routes/sentinelle'
import { Route as TableauRouteImport } from './routes/tableau'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as ApiSatRouteImport } from './routes/api/sat'
import { Route as ApiTileRouteImport } from './routes/api/tile'
import { Route as ApiZoneGpsRouteImport } from './routes/api/zone-gps'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const CapteursRoute = CapteursRouteImport.update({
  id: '/capteurs',
  path: '/capteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionRoute = DivisionRouteImport.update({
  id: '/division',
  path: '/division',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentRoute = IdentRouteImport.update({
  id: '/ident',
  path: '/ident',
  getParentRoute: () => rootRouteImport,
} as any)
const IffRoute = IffRouteImport.update({
  id: '/iff',
  path: '/iff',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartRoute = QuartRouteImport.update({
  id: '/quart',
  path: '/quart',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelleRoute = SentinelleRouteImport.update({
  id: '/sentinelle',
  path: '/sentinelle',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauRoute = TableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSatRoute = ApiSatRouteImport.update({
  id: '/api/sat',
  path: '/api/sat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTileRoute = ApiTileRouteImport.update({
  id: '/api/tile',
  path: '/api/tile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZoneGpsRoute = ApiZoneGpsRouteImport.update({
  id: '/api/zone-gps',
  path: '/api/zone-gps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/capteurs': typeof CapteursRoute
  '/catalogue': typeof CatalogueRoute
  '/division': typeof DivisionRoute
  '/ident': typeof IdentRoute
  '/iff': typeof IffRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/quart': typeof QuartRoute
  '/radar': typeof RadarRoute
  '/sentinelle': typeof SentinelleRoute
  '/tableau': typeof TableauRoute
  '/trace': typeof TraceRoute
  '/zones': typeof ZonesRoute
  '/api/sat': typeof ApiSatRoute
  '/api/tile': typeof ApiTileRoute
  '/api/zone-gps': typeof ApiZoneGpsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/capteurs': typeof CapteursRoute
  '/catalogue': typeof CatalogueRoute
  '/division': typeof DivisionRoute
  '/ident': typeof IdentRoute
  '/iff': typeof IffRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/quart': typeof QuartRoute
  '/radar': typeof RadarRoute
  '/sentinelle': typeof SentinelleRoute
  '/tableau': typeof TableauRoute
  '/trace': typeof TraceRoute
  '/zones': typeof ZonesRoute
  '/api/sat': typeof ApiSatRoute
  '/api/tile': typeof ApiTileRoute
  '/api/zone-gps': typeof ApiZoneGpsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/capteurs': typeof CapteursRoute
  '/catalogue': typeof CatalogueRoute
  '/division': typeof DivisionRoute
  '/ident': typeof IdentRoute
  '/iff': typeof IffRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/quart': typeof QuartRoute
  '/radar': typeof RadarRoute
  '/sentinelle': typeof SentinelleRoute
  '/tableau': typeof TableauRoute
  '/trace': typeof TraceRoute
  '/zones': typeof ZonesRoute
  '/api/sat': typeof ApiSatRoute
  '/api/tile': typeof ApiTileRoute
  '/api/zone-gps': typeof ApiZoneGpsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/capteurs'
    | '/catalogue'
    | '/division'
    | '/ident'
    | '/iff'
    | '/journal'
    | '/login'
    | '/quart'
    | '/radar'
    | '/sentinelle'
    | '/tableau'
    | '/trace'
    | '/zones'
    | '/api/sat'
    | '/api/tile'
    | '/api/zone-gps'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/capteurs'
    | '/catalogue'
    | '/division'
    | '/ident'
    | '/iff'
    | '/journal'
    | '/login'
    | '/quart'
    | '/radar'
    | '/sentinelle'
    | '/tableau'
    | '/trace'
    | '/zones'
    | '/api/sat'
    | '/api/tile'
    | '/api/zone-gps'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/capteurs'
    | '/catalogue'
    | '/division'
    | '/ident'
    | '/iff'
    | '/journal'
    | '/login'
    | '/quart'
    | '/radar'
    | '/sentinelle'
    | '/tableau'
    | '/trace'
    | '/zones'
    | '/api/sat'
    | '/api/tile'
    | '/api/zone-gps'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  CapteursRoute: typeof CapteursRoute
  CatalogueRoute: typeof CatalogueRoute
  DivisionRoute: typeof DivisionRoute
  IdentRoute: typeof IdentRoute
  IffRoute: typeof IffRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  QuartRoute: typeof QuartRoute
  RadarRoute: typeof RadarRoute
  SentinelleRoute: typeof SentinelleRoute
  TableauRoute: typeof TableauRoute
  TraceRoute: typeof TraceRoute
  ZonesRoute: typeof ZonesRoute
  ApiSatRoute: typeof ApiSatRoute
  ApiTileRoute: typeof ApiTileRoute
  ApiZoneGpsRoute: typeof ApiZoneGpsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capteurs': {
      id: '/capteurs'
      path: '/capteurs'
      fullPath: '/capteurs'
      preLoaderRoute: typeof CapteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/division': {
      id: '/division'
      path: '/division'
      fullPath: '/division'
      preLoaderRoute: typeof DivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ident': {
      id: '/ident'
      path: '/ident'
      fullPath: '/ident'
      preLoaderRoute: typeof IdentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iff': {
      id: '/iff'
      path: '/iff'
      fullPath: '/iff'
      preLoaderRoute: typeof IffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quart': {
      id: '/quart'
      path: '/quart'
      fullPath: '/quart'
      preLoaderRoute: typeof QuartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinelle': {
      id: '/sentinelle'
      path: '/sentinelle'
      fullPath: '/sentinelle'
      preLoaderRoute: typeof SentinelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau': {
      id: '/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof TableauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sat': {
      id: '/api/sat'
      path: '/api/sat'
      fullPath: '/api/sat'
      preLoaderRoute: typeof ApiSatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tile': {
      id: '/api/tile'
      path: '/api/tile'
      fullPath: '/api/tile'
      preLoaderRoute: typeof ApiTileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zone-gps': {
      id: '/api/zone-gps'
      path: '/api/zone-gps'
      fullPath: '/api/zone-gps'
      preLoaderRoute: typeof ApiZoneGpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  CapteursRoute: CapteursRoute,
  CatalogueRoute: CatalogueRoute,
  DivisionRoute: DivisionRoute,
  IdentRoute: IdentRoute,
  IffRoute: IffRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  QuartRoute: QuartRoute,
  RadarRoute: RadarRoute,
  SentinelleRoute: SentinelleRoute,
  TableauRoute: TableauRoute,
  TraceRoute: TraceRoute,
  ZonesRoute: ZonesRoute,
  ApiSatRoute: ApiSatRoute,
  ApiTileRoute: ApiTileRoute,
  ApiZoneGpsRoute: ApiZoneGpsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
